const ship = "p";
const bullet = "f";      // Player laser bullet
const enemy = "e";       // Enemy spaceship
const enemyBullet = "g"; // Enemy laser bullet
const heart = "h";       // Health UI heart sprite
const skull = "x";       // Game Over icon sprite
const dark = "b";

function randomInt(max) {
  return Math.floor(Math.random() * max);
}

// === Audio Effects ===
function playShootSfx() {
  try {
    playTune("100: C6-20, G5-20");
  } catch (e) {}
}

function playDamageSfx() {
  try {
    playTune("100: E3-30, C3-30, G2-30");
  } catch (e) {}
}

// === Star Generator ===
function generateStarBitmap() {
  const px = 3 + randomInt(10);
  const py = 3 + randomInt(10);

  let rows = [];
  for (let y = 0; y < 16; y++) {
    let row = "";
    for (let x = 0; x < 16; x++) {
      row += (x === px && y === py) ? "2" : ".";
    }
    rows.push(row);
  }
  return rows.join("\n");
}

const starTypes = ["k", "l", "m", "n", "o", "q", "r", "t", "u", "v"];

// Digit Bitmaps for Score Display (0-9)
const digitBitmaps = {
  "0": bitmap`
................
.....66666......
.....6...6......
.....6...6......
.....6...6......
.....66666......
................
................
................
................
................
................
................
................
................
................`,
  "1": bitmap`
................
.......66.......
......666.......
.......66.......
.......66.......
.....666666.....
................
................
................
................
................
................
................
................
................
................`,
  "2": bitmap`
................
.....66666......
.........6......
.....66666......
.....6..........
.....66666......
................
................
................
................
................
................
................
................
................
................`,
  "3": bitmap`
................
.....66666......
.........6......
.....66666......
.........6......
.....66666......
................
................
................
................
................
................
................
................
................
................`,
  "4": bitmap`
................
.....6...6......
.....6...6......
.....66666......
.........6......
.........6......
................
................
................
................
................
................
................
................
................
................`,
  "5": bitmap`
................
.....66666......
.....6..........
.....66666......
.........6......
.....66666......
................
................
................
................
................
................
................
................
................
................`,
  "6": bitmap`
................
.....66666......
.....6..........
.....66666......
.....6...6......
.....66666......
................
................
................
................
................
................
................
................
................
................`,
  "7": bitmap`
................
.....66666......
.........6......
........6.......
.......6........
......6.........
................
................
................
................
................
................
................
................
................
................`,
  "8": bitmap`
................
.....66666......
.....6...6......
.....66666......
.....6...6......
.....66666......
................
................
................
................
................
................
................
................
................
................`,
  "9": bitmap`
................
.....66666......
.....6...6......
.....66666......
.........6......
.....66666......
................
................
................
................
................
................
................
................
................
................`
};

const legendItems = [
  [ dark, bitmap`
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000` ]
];

starTypes.forEach((typeId) => {
  legendItems.push([ typeId, generateStarBitmap() ]);
});

Object.keys(digitBitmaps).forEach((d) => {
  legendItems.push([ d, digitBitmaps[d] ]);
});

legendItems.push(
  [ heart, bitmap`
................
..333......333..
.33333....33333.
.333333..333333.
..333333333333..
...3333333333...
....33333333....
.....333333.....
......3333......
.......33.......
................
................
................
................
................
................` ],
  [ skull, bitmap`
.....333333.....
...3333333333...
..33.333333.33..
..33.333333.33..
..333333333333..
...33.3..3.33...
....333..333....
......3333......
.....3.3.3.3....
.....3.3.3.3....
................
................
................
................
................
................` ],
  [ enemy, bitmap`
................
................
................
................
1111311111311111
.1113111113111..
..11311111311...
...131111131....
....3111113.....
.....11111......
......111.......
.......1........
................
................
................
................` ],
  [ enemyBullet, bitmap`
................
................
.......6........
.......6........
.......6........
.......6........
................
................
................
................
................
................
................
................
................
................` ],
  [ bullet, bitmap`
................
................
.......3........
.......3........
.......3........
.......3........
................
................
................
................
................
................
................
................
................
................` ],
  [ ship, bitmap`
................
................
..2..........2..
..1..........1..
..1..........1..
..1....11....1..
..1....11....1..
..1...1111...1..
..1..111111..1..
.11..111111..11.
1117711111177111
1117711111177111
1117711111177111
.....111111.....
......1111......
................` ]
);

setLegend(...legendItems);
setBackground(dark);

const level = map`
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
.......p.......`;
setMap(level);

const maxPlayerHealth = 3;
let currentHealth = maxPlayerHealth;
let score = 0;
let isGameOver = false;

function renderHealthUI() {
  getAll(heart).forEach(h => h.remove());
  for (let i = 0; i < currentHealth; i++) {
    addSprite(i, 0, heart);
  }
}
renderHealthUI();

function triggerGameOver() {
  isGameOver = true;

  [
    ...getAllStars(),
    ...getAll(enemy),
    ...getAll(bullet),
    ...getAll(enemyBullet),
    ...getAll(heart)
  ].forEach(s => s.remove());

  const myShip = getFirst(ship);
  if (myShip) myShip.remove();

  const centerX = Math.floor(width() / 2);
  const centerY = Math.floor(height() / 2) - 1;
  addSprite(centerX, centerY, skull);

  const scoreStr = score.toString();
  const startX = Math.floor((width() - scoreStr.length) / 2);
  for (let i = 0; i < scoreStr.length; i++) {
    addSprite(startX + i, centerY + 2, scoreStr[i]);
  }
}

function restartGame() {
  const skullSprite = getFirst(skull);
  if (skullSprite) skullSprite.remove();

  for (let i = 0; i <= 9; i++) {
    getAll(i.toString()).forEach(s => s.remove());
  }

  [...getAll(enemy), ...getAll(bullet), ...getAll(enemyBullet)].forEach(s => s.remove());

  score = 0;
  currentHealth = maxPlayerHealth;
  isGameOver = false;

  addSprite(Math.floor(width() / 2), height() - 1, ship);
  renderHealthUI();

  for (let i = 0; i < totalStars; i++) {
    spawnStar(randomInt(width()), randomInt(height()));
  }
}

function spawnStar(x, y) {
  const randomType = starTypes[randomInt(starTypes.length)];
  return addSprite(x, y, randomType);
}

function getAllStars() {
  let stars = [];
  for (let type of starTypes) {
    stars = stars.concat(getAll(type));
  }
  return stars;
}

function getUniqueX() {
  const activeX = getAllStars().map(s => s.x);
  let x = randomInt(width());
  let attempts = 0;
  while (activeX.includes(x) && attempts < 15) {
    x = randomInt(width());
    attempts++;
  }
  return x;
}

const totalStars = 9;
for (let i = 0; i < totalStars; i++) {
  spawnStar(randomInt(width()), randomInt(height()));
}

function checkBulletHit(b) {
  const hitEnemy = getAll(enemy).find(e => e.x === b.x && e.y === b.y);
  if (hitEnemy) {
    b.remove();
    hitEnemy.remove();
    score += 1;
    return true;
  }
  return false;
}

// === Background Stars Scrolling ===
setInterval(() => {
  if (isGameOver) return;
  getAllStars().forEach((st) => {
    if (st.y + 1 >= height()) {
      st.remove();
      spawnStar(getUniqueX(), 0);
    } else {
      st.y += 1;
    }
  });
}, 250);

// === Enemy Spawning Loop ===
setInterval(() => {
  if (isGameOver) return;
  const maxEnemies = Math.min(6, 3 + Math.floor(score / 8));
  if (getAll(enemy).length < maxEnemies) {
    addSprite(randomInt(width()), 0, enemy);
  }
}, 1000);

// === Enemy Movement & Collision Loop ===
setInterval(() => {
  if (isGameOver) return;
  const myShip = getFirst(ship);

  getAll(enemy).forEach((e) => {
    if (e.y + 1 >= height()) {
      e.remove();
    } else {
      const incomingBullet = getAll(bullet).find(b => b.x === e.x && b.y === e.y + 1);
      if (incomingBullet) {
        e.remove();
        incomingBullet.remove();
        score += 1;
        return;
      }

      e.y += 1;

      const hitBullet = getAll(bullet).find(b => b.x === e.x && b.y === e.y);
      if (hitBullet) {
        e.remove();
        hitBullet.remove();
        score += 1;
        return;
      }

      if (myShip && e.x === myShip.x && e.y === myShip.y) {
        e.remove();
        currentHealth -= 1;
        playDamageSfx();
        renderHealthUI();
        if (currentHealth <= 0) triggerGameOver();
      }
    }
  });
}, 450);

// === Enemy Shooting Loop ===
setInterval(() => {
  if (isGameOver) return;
  getAll(enemy).forEach((e) => {
    if (e.y < height() - 1) {
      addSprite(e.x, e.y + 1, enemyBullet);
    }
  });
}, 1800);

// === Enemy Bullet Movement Loop ===
setInterval(() => {
  if (isGameOver) return;
  const myShip = getFirst(ship);

  getAll(enemyBullet).forEach((eb) => {
    if (eb.y >= height() - 1) {
      eb.remove();
    } else {
      eb.y += 1;

      if (myShip && eb.x === myShip.x && eb.y === myShip.y) {
        eb.remove();
        currentHealth -= 1;
        playDamageSfx();
        renderHealthUI();
        if (currentHealth <= 0) triggerGameOver();
      }
    }
  });
}, 110);

// === Player Bullet Movement Loop ===
setInterval(() => {
  if (isGameOver) return;
  getAll(bullet).forEach((b) => {
    if (checkBulletHit(b)) return;

    if (b.y <= 0) {
      b.remove();
    } else {
      b.y -= 1;
      checkBulletHit(b);
    }
  });
}, 60);

// === Controls ===
function handleInput(moveAction) {
  if (isGameOver) {
    restartGame();
    return;
  }
  moveAction();
}

onInput("w", () => handleInput(() => {
  const myShip = getFirst(ship);
  if (myShip && myShip.y > 0) myShip.y -= 1;
}));
onInput("s", () => handleInput(() => {
  const myShip = getFirst(ship);
  if (myShip && myShip.y < height() - 1) myShip.y += 1;
}));
onInput("a", () => handleInput(() => {
  const myShip = getFirst(ship);
  if (myShip && myShip.x > 0) myShip.x -= 1;
}));
onInput("d", () => handleInput(() => {
  const myShip = getFirst(ship);
  if (myShip && myShip.x < width() - 1) myShip.x += 1;
}));

function shoot() {
  if (isGameOver) {
    restartGame();
    return;
  }
  const myShip = getFirst(ship);
  if (myShip && myShip.y > 0) {
    addSprite(myShip.x, myShip.y - 1, bullet);
    playShootSfx();
  }
}

onInput("j", shoot);
onInput("i", shoot);