/*
@title: Alien Blast
@author: Aloys
@description: A simple space shooter where you kill aliens before they reach you
@tags: [alien, shooter, arcade]
@addedOn: 2025-08-25
*/

// === Sprite definitions ===
const player = "p"
const alien = "a"
const bullet = "b"

// Global variables
let score = 0
let gameOver = false

// Sprite graphics
setLegend(
  [ player, bitmap`
......33........
.....3333.......
....333333......
....333333......
.....3333.......
......33........
................
................
................
................
................
................
................
................
................
................` ],
  [ alien, bitmap`
...55555555.....
..5555555555....
..5555..5555....
..5555555555....
...55555555.....
................
................
................
................
................
................
................
................
................
................` ],
  [ bullet, bitmap`
......33........
......33........
......33........
......33........
................
................
................
................
................
................
................
................
................
................
................
................` ]
)

// Starting map
const startMap = map`
..........
..........
..........
..........
..........
..........
..........
..........
p.........`
setMap(startMap)

// Collision settings
setSolids([ player ])
setPushables({ [ player ]: [] })

// === Utility functions ===

// End screen
function gameOverScreen() {
  gameOver = true
  addText("GAME OVER", { x: 4, y: 4, color: color`3` })
}

// === Player controls ===
onInput("a", () => {
  if (gameOver) return
  let ship = getFirst(player)
  if (ship.x > 0) ship.x -= 1
})

onInput("d", () => {
  if (gameOver) return
  let ship = getFirst(player)
  if (ship.x < width() - 1) ship.x += 1
})

onInput("w", () => {
  if (gameOver) return
  let ship = getFirst(player)
  addSprite(ship.x, ship.y - 1, bullet)
})

// === Game mechanics ===

// Bullet movement
setInterval(() => {
  if (gameOver) return

  let allBullets = getAll(bullet)
  for (let b of allBullets) {
    b.y -= 1
    if (b.y < 0) b.remove() // Remove bullets off-screen
  }
}, 150)

// Alien spawning
setInterval(() => {
  if (gameOver) return

  let randomX = Math.floor(Math.random() * width())
  addSprite(randomX, 0, alien)
}, 700)

// Alien movement
setInterval(() => {
  if (gameOver) return

  let allAliens = getAll(alien)
  for (let a of allAliens) {
    a.y += 1
    if (a.y >= height() - 1) {
      gameOverScreen()
    }
  }
}, 500)

// Bullet/alien collision detection
afterInput(() => {
  if (gameOver) return

  let allBullets = getAll(bullet)
  let allAliens = getAll(alien)

  for (let b of allBullets) {
    for (let a of allAliens) {
      if (b.x === a.x && b.y === a.y) {
        b.remove()
        a.remove()
        score += 1
      }
    }
  }
})

// Score display
setInterval(() => {
  if (gameOver) return
  clearText()
  addText(`Score: ${score}`, { x: 4, y: 0, color: color`0` })
}, 100)