/*
@title: alien
@author: anshimathur0325
move the player with "a" and "d" for left and right
move the lazer up with "w"
if the lazer reaches the top without hitting an alien you lose one point. 
you gain a point when you hit an alien. 
*/

const player="p";
const alien="w";
const lazer="c";
let score = 0;
setLegend(
  [ player, bitmap`
.......11.......
......1111......
.....111111.....
.....111111.....
.....111111.....
.11111111111111.
....5......5....
....5.0.0..5.0..
..0.5......50...
...05.000..5....
....5......5....
....5......5....
.....555555.....
.......0.0......
.......0.0......
.......0.0......`],
  [ alien, bitmap`
................
................
................
...4.......4....
....4.....4.....
.....44444......
.....40404......
.....40404......
.....44444......
...000000000....
..00000000000...
..00807060300...
................
................
................
................`],
  [ lazer, bitmap`
................
................
................
.....66666......
.....66666......
.....66666......
.....66666......
.....66666......
.....66666......
.....66666......
.....66666......
.....66666......
................
................
................
................`]
  
);
//lazer movement
onInput("w", () => {
  for (let i = 0; i < 1; i++) {
  getFirst(lazer).y -=1;
  
}

//player movement with lazer
});
onInput("d", () => {
  getFirst(player).x += 1;
});

onInput("a", () => {
  getFirst(player).x -= 1;
});
onInput("d", () => {
  getFirst(lazer).x += 1;
});

onInput("a", () => {
  getFirst(lazer).x -= 1;
});

//countdown timer
var timeleft = 10;
    var downloadTimer = setInterval(function(){
    timeleft--;
    addText("Time Left: "+timeleft, { y: 1 });
      if(timeleft <= 0){
        clearTile(getFirst(lazer).x,getFirst(lazer).y);
        clearInterval(downloadTimer);
        clearText()
        addText("Final Score: "+score, {y:4});

    }
    },1000);

//map location
setMap( map`
..........
..........
..........
..w.......
..........
..........
..........
..........
c.........
p.........`);


afterInput(() => {
  // count the number of tiles with lazer
  const targetNumber = tilesWith(lazer).length;
  
  // count the number of tiles with lazers and aliens
  const numberCovered = tilesWith(lazer, alien).length;

  //resets the lazer if it misses the alien
  //and removes a point from the lazer. 
  if (getFirst(lazer).y==0){
    clearTile(getFirst(lazer).x,getFirst(lazer).y);
    addSprite(getFirst(player).x, 8, lazer);
    score--;
  }
  
  //removes the hit alien and lazer, puts another alien in a random spot
  //and restores the lazer to the player. 
  //Also adds a point to the score. 
  if (numberCovered === targetNumber) {
    clearTile(getFirst(lazer).x,getFirst(alien).y);
    addSprite(getFirst(player).x, 8, lazer);
    addSprite(Math.floor(Math.random() * 8), Math.floor(Math.random() * 8), alien);
    score++;
  }

  //Displays the score. 
  addText("score: "+score, { y: 4 });
  
});




