/*
@title: A Long Fall
@description: A game where you fall and need to avoid obstacles !
@author: skueee
@tags: ['fall', 'levels', 'fast']
@addedOn: 2026-10-07
*/

const player = "p"
const wall = "w"

let gameOver = false

setLegend(
  [player, bitmap`
....00000000....
...0000000000...
..000......000..
.00..........00.
000..........000
00............00
00...0....0...00
00............00
00.....00.....00
00............00
00............00
000..........000
.00..........00.
..000......000..
...0000000000...
....00000000....`],
  [wall, bitmap`
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000`],
)

let level = 0;

const levels = [
  map`
................
.......p........
................
................
wwwwww..........
..........wwwwww
................
................
................
................
......ww.w......
................
wwwwwww..wwwwwww
................
................
........w.......`,
  map`
........p.......
................
................
........wwwwwwww
................
................
wwwwwww.........
................
.......w........
wwwwwwww.w.w.w.w
................
................
................
www.w.w.w.w.w.ww
................
................`,
  map`
................
.......p........
................
................
......wwww......
..........wwwwww
wwwww...........
.....ww.........
................
................
wwwwwww.wwwwwwww
................
................
.......w........
................
................`,
  map`
................
.......p........
................
wwww.w.w.w.wwwww
...w.w.w.w.w....
...w.w.w.w.w....
...w.......w....
...w.......w....
....w.....w.....
.....w...w......
................
......www.......
................
wwww.wwwww.wwwww
................
w.w.w.w.w.w.w.w.`,
  map`
................
.......p........
................
wwwww.....wwwwww
.....w...w......
......w.w.......
........w.......
.......w........
.......w........
...w..w.........
.......w........
................
..w..w..........
......www.......
.w..w...........
................`,
  map`
................
.......p........
..w..........w..
..w..........w..
..w..........w..
..w..........w..
..w..........w..
..wwwwww.wwwww..
..w..........w..
..w..........w..
..w..........w..
..w.............
..w.............
..w.............
wwwwwwwwwww.....
wwwwwwwwwwwww...`,
  map`
................
.......p........
................
................
......w.ww......
......w..w......
......w..w......
......w..w......
......w..w......
.........w......
.......www......
................
................
.....ww.........
....w...........
................`,
  map`
................
.......p........
................
................
................
................
wwwwwwwwww......
..........w..www
.........w......
.........w......
.........w...w..
..........w...ww
......wwww......
................
...........ww...
w.w.w.w.w.w.w.w.`,
  map`
......w.w.......
......wpw.......
......w.w.......
....ww...ww.....
...w.......w....
..w....w....w...
..w.........w...
...ww.....ww....
.......w........
.....w...w......
................
..............ww
....ww......ww..
..ww..ww...w....
ww.......ww.....
................`,
  map`
................
.......p........
.....w....w.....
......w..w......
................
................
........w.......
.......w.w......
wwwwww.....wwwww
..........w.....
.....w.www......
.....w.w........
.......w........
......w.........
.....w..........
....w...........`,
  map`
  p...............
  .w..............
  .w..............
  ..w.............
  w.w.............
  w.w.............
  w..w............
  .w..w...........
  ..w.w...........
  .w..w...........
  w....w..........
  www.............
  ................
  w.w.w.w.w.w.w.w.
  ................
  .w.w.w.w.w.w.w.w`,
  map`
  ...............p
  wwwwwwwwwwwwwww.
  ................
  wwwwwwwwwwwwww.w
  ................
  wwwwwwwwwwww..ww
  wwwwwwwwwwwww.ww
  wwwwwwwwwwww..ww
  wwwwwwwwwww..www
  wwwwwwwww...wwww
  ................
  ................
  ................
  ww.ww.ww.ww.ww.w
  ................
  wwwwwww..wwwwwww`,
  map`
  .......p........
  ................
  ......www.......
  wwww.w...w.wwwww
  ................
  w.w.w.w.w.w.w.w.
  ................
  .w.w.w.w.w.w.w.w
  ................
  ................
  .ww.ww.ww.ww.ww.
  ................
  ww.ww.ww.ww.ww.w
  ................
  w.w.w.w.w.w.w.w.
  www.www.www.www.`,
  map`
  w....p..........
  .w..............
  ..w.............
  ...w............
  ....w...........
  .....wwww.......
  wwwwwwwww.wwwwww
  wwwwwwwww..wwwww
  wwwwwwww..wwwwww
  wwwwwwww.wwwwwww
  ............wwww
  wwwwwwww........
  .........wwwwwww
  wwwwwww.........
  ................
  ................`,
]

onInput("d", () => {
  if (!gameOver) {
    getFirst(player).x += 1;
    checkCollision()
  }
});

onInput("a", () => {
  if (!gameOver) {
    getFirst(player).x -= 1;
    checkCollision()
  }
});

let speed = 300

function addLevelText() {
  clearText()
  addText(`Level ${level + 1}`, { x: 6, y: 0, color: color`0` })
}

function checkCollision() {
  if (getTile(getFirst(player).x, getFirst(player).y).some(s => s.type === wall)) {
    gameover()
  }
}

function setLevel() {
  const currentLevel = levels[level];
  setMap(currentLevel)
  addLevelText()
}

function fall() {
  if (getFirst(player).y < 15) {
    getFirst(player).y += 1
    checkCollision()
    if (!gameOver) {
      setTimeout(fall, speed)
    }
  } else {
    level += 1
    if (levels.length > level) {
      if (speed > 50) {
        speed -= 5
      }
      setLevel()
      setTimeout(fall, speed + 250)
    } else {
      won()
    }
  }
}

setLevel()
fall()

function gameover() {
  gameOver = true;
  setMap(map`
wwwwww
wwwwww
wwwwww
wwwwww
wwwwww`);
  clearText();
  addText(`Game over!\n\nLevel ${level + 1}`, { x: 2, y: 6, color: color`3` })
}

function won() {
  gameOver = true;
  setMap(map`
wwwwww
wwwwww
wwwwww
wwwwww
wwwwww`);
  clearText();
  addText(`You won!\n\nGood job :3`, { x: 2, y: 6, color: color`4` })
}