/*
@title: Antony
@author: Chee Yong Lee
@tags: ['puzzle']
@addedOn: 2025-08-05
@description: The objective of the game is to lead Antony to collect crumbs and proceed to the next room.

Instructions:

Click "run" to start the game

The objective is to collect the crumbs and find the way out to the next room
*/


const ant = "a"
const wall = "w"
const crumb = "c"
const exit = "e"
const floor = "f"

setLegend(
  [ ant, bitmap`
................
................
.......66.......
......6006......
......0660......
......0660......
......6666......
......0660......
.....006600.....
.....006600.....
......0660......
......0660......
......0660......
......0000......
................
................` ],
  [ wall, bitmap`
CCC11CCCC1CCCC1C
CCC11CCCC1CCCC1C
11CCCC1CCCCC1CCC
11CCCC1CCCCC1CCC
CCC1111111111111
11CCCCCCC1111CCC
CCCCCCCCCCCCCCCC
CCC111CCCCCCC111
1CCCCCC111CCC111
1C1111CCCCC1CCCC
1CCCCCC111C11111
11C111CCCCC11111
CCC11111CCCCCCCC
CCCCCCCCC1111111
1C11C111CCCCCCCC
1C11C111C111C111` ],
  [ crumb, bitmap`
................
................
......4444......
.....446644.....
.....446644.....
......4444......
................
................
................
................
................
................
................
................
................
................` ],
  [ exit, bitmap`
................
................
......9999......
.....9...99.....
....9.....99....
....9......9....
....9......9....
.....9....9.....
......9999......
................
................
................
................
................
................
................` ],
  [ floor, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................` ]
)

setSolids([ant, wall])
setPushables({ [ant]: [] })

let level = 0

const levels = [
  map`
wwwwwwww
wa....cw
w...w..w
w.c.w..w
w.www..w
w...c..w
w......w
wwwwwwww`,
  map`
wwwwwwww
w.c....w
w..ww..w
w.a....w
w..w.c.w
w.c....w
w......w
wwwwwwww`,
  map`
wwwwwwww
w.c.a..w
w..ww..w
w.c....w
w..w.c.w
w...c..w
w......w
wwwwwwww`,
`wwwwwwww
w.c.a..w
w...w..w
w.c....w
w..w.c.w
w.w....w
w...c..w
wwwwwwww`
]

setMap(levels[level])
setBackground(floor)

function checkCrumbs() {
  if (tilesWith(crumb).length === 0 && tilesWith(exit).length === 0) {
    const centerX = 3
    const centerY = 6
    addSprite(centerX, centerY, exit)
  }
}

function checkWin() {
  if (tilesWith(ant, exit).length > 0) {
    level++
    if (level < levels.length) {
      setMap(levels[level])
    } else {
      addText("Antony Wins!", { y: 4, color: color`0` })
    }
  }
}

onInput("w", () => moveAnt(0, -1))
onInput("s", () => moveAnt(0, 1))
onInput("a", () => moveAnt(-1, 0))
onInput("d", () => moveAnt(1, 0))

function moveAnt(dx, dy) {
  const antSprite = getFirst(ant)
  const newX = antSprite.x + dx
  const newY = antSprite.y + dy
  const tile = getTile(newX, newY)

  if (!tile.some(t => t.type === wall)) {
    antSprite.x = newX
    antSprite.y = newY

    if (tile.some(t => t.type === crumb)) {
      clearTile(newX, newY)
      addSprite(newX, newY, floor)
      addSprite(newX, newY, ant)
    }

    checkCrumbs()
    checkWin()
  }
}
