/*
@title: balloon
@author: LucasHT22
*/

const player = "p";
const prego = "o";
const final = "f";

setLegend(
  [ player, bitmap`
................
................
.......555......
......55555.....
......55555.....
......55555.....
......55555.....
.......555......
........5.......
........5.......
.........5......
........5.......
.......5........
........5.......
.........5......
................`],
  [ prego, bitmap`
.0..0......0....
...0.........0..
....0..0..0.....
.0..............
....0.0..0.0..0.
0.0.............
..0...0.0....0..
..0..0..0.......
..0.......00..0.
0...0.0..0....0.
0.0......0..0...
................
....0..0...0..0.
.0..0...........
...........0....
........0.......`],
  [ final, bitmap`
................
................
................
................
...666666666....
...666666666....
...666666666....
...666666666....
...666666666....
...666666666....
...666666666....
...666666666....
...666666666....
................
................
................`]
);
  
let level = 0;
const levels = [
  map`
o...
..o.
pof.`,
  map`
pof.
.oo.
....`,
  map`
.o...ofooo
.o.o.o....
...o.oooo.
...o...o..
.o...o.o.o
po.o.o...o`,
];
const faseAtual = levels[level];
setMap(faseAtual);

setMap(levels[level]);

setPushables({
  [ player ]: [],
});

onInput("w", () => {
  getFirst(player).y -= 1;
});

onInput("s", () => {
  getFirst(player).y += 1;
});

onInput("a", () => {
  getFirst(player).x -= 1;
});

onInput("d", () => {
  getFirst(player).x += 1;
});

onInput("j", () => {
  const faseAtual = levels[level];
  if (faseAtual !== undefined) setMap(faseAtual);
});

setSolids([prego, player]);

afterInput(() => {
  const atual = tilesWith(player, final).length;
  const f2 = tilesWith(final).length;
   if (atual === f2) {
    level = level + 1;

    const faseAtual = levels[level];

    if (faseAtual !== undefined) {
      setMap(faseAtual);
    } else {
      addText("voce venceu!")
    }
  }
});