/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

@title: 
@author: 
@tags: []
@addedOn: 2024-00-00
*/
let ui = 'u'
let loading_screen = 'l'
let cookie_big = 'c'
let cookie_small = 's'

setLegend(
  [ui, bitmap`
................
......CCCCC.....
.....CCLCCCC....
.....CCCCLCC....
.....CCCCCCC....
.....CCLCCCC....
.....CCCCLCC....
......CCCCC.....
................
........0.......
......DDDDD.....
......D.0.......
......DDDDD.....
........0.D.....
......DDDDD.....
........0.......`,],
   [loading_screen, bitmap`
................
................
...4444.44444...
...4....4...4...
...4.44.4...4...
...4..4.4...4...
...4444.44444...
................
..L..........L..
.L.L........L.L.
..L..........L..
................
................
................
................
................`],
  [cookie_big, bitmap`
................
....CCCCCCCC....
...CCCCLCCCCC...
..CCCLCCCLCCCC..
.CCCCCCCCCCCCCC.
.CCLCCCLCLCCCLC.
.CCCCCCCCCCCCCC.
.CCCLCCCCCCCCCC.
.CCCCCCCLCCCLCC.
.CCLCLCCCCCCCCC.
.CCCCCCLCCLCCCC.
.CCCCLCCCCCCCCC.
..CCCCCCCLCCCC..
...CCCCCCCCCC...
....CCCCCCCC....
................`],
  [cookie_small, bitmap`
................
................
..1..........1..
...1........1...
....1CCCCCC1....
....CCCCCLCC....
...CCLCCCCCCC...
...CCCCCLCCLC...
...CCCLCCCCCC...
...CCLCCCLCCC...
...CCCCCCCCCC...
....CCCLCCCC....
....1CCCCCC1....
...1........1...
..1..........1..
................`]
)

setSolids([])
let money = 0
let cookies = 0
let level = 0
let is_in_main_game = 0
const levels = [
  map`
u...
....
....
c...`, map`
l`
]
setMap(levels[1])
addText("Press S to start", {
  x:2,
  y:13,
  color: color`0`,})

/*Loading screen*/
onInput('s', () => {
  if (is_in_main_game == 0) {
  setMap(levels[0])
  clearText()
  is_in_main_game = 1}
  else {
    cookies += 1
    clearTile(0,3)
    addSprite(0,3,cookie_small)
    setTimeout(() => {
    clearTile(0,3)
    addSprite(0,3,cookie_big)
    }, 100)

  }
    set_displays(money, cookies)
})
setTimeout(() => {
  // Code to be executed after the pause
  console.log("Operation after pause");
}, 1000);


function set_displays(money, cookies) {
  addText(money.toString(), { 
  x: 6,
  y: 3,
  color: color`0`})
  addText(cookies.toString(), { 
  x: 6,
  y: 1,
  color: color`0`
})
}

function sell_cookies() {
  money += Math.pow(cookies, 1.4)
  cookies = 0
  
}

