const player = "p"
const block1 = "b"
const block2 = "c"
const block3 = "d"
const block4 = "e"
const portal = "o"

setLegend(
  [ player, bitmap`
................
................
......00000.....
......05.50.....
......0...0.....
......0CCC0.....
......00000.....
........0.......
......00000.....
....00..0..00...
...0...000...0..
.......0.0......
.......000......
......00.00.....
.....0.....0....
....0.......0...` ],

  [ block1, bitmap`
................
................
....3333........
....3333........
....3333........
....3333........
................
................
................
................
................
................
................
................
................
................` ],

  [ block2, bitmap`
................
...333333.......
...333333.......
...333333.......
...333333.......
...333333.......
...333333.......
................
................
................
................
................
................
................
................
................` ],

  [ block3, bitmap`
..33333333......
..33333333......
..33333333......
..33333333......
..33333333......
..33333333......
..33333333......
..33333333......
................
................
................
................
................
................
................
................` ],

  [ block4, bitmap`
.3333333333.....
.3333333333.....
.3333333333.....
.3333333333.....
.3333333333.....
.3333333333.....
.3333333333.....
.3333333333.....
.3333333333.....
................
................
................
................
................
................
................` ],

  [ portal, bitmap`
................
......666666....
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
.....6......6...
......666666....
................` ]
)

const levels = [
  map`
...........
...........
...........
...........
...........
..p........
...........
...........
...........
...........
...........`
]

setSolids([])
setPushables({ [player]: [] })

let level = 0
let gameOver = false
let spawnLoop
let moveLoop

function currentBlock() {
  if (level === 0) return block1
  if (level === 1) return block2
  if (level === 2) return block3
  return block4
}

function startLevel() {
  clearText()
  clearInterval(spawnLoop)
  clearInterval(moveLoop)

  setMap(levels[0])
  gameOver = false

  addText("Level " + (level + 1), { x: 3, y: 5, color: color`2` })

  spawnLoop = setInterval(() => {
    if (gameOver) return
    addSprite(10, Math.floor(Math.random() * 11), currentBlock())
  }, Math.max(400, 1000 - level * 150))

  moveLoop = setInterval(() => {
    if (gameOver) return

    getAll(block1)
      .concat(getAll(block2))
      .concat(getAll(block3))
      .concat(getAll(block4))
      .forEach(b => {
        b.x -= 1

    
        if (b.x <= 0) {

  setTimeout(() => b.remove(), 500)
}
      })

  }, Math.max(80, 250 - level * 40))

  setTimeout(() => {
    if (!gameOver) {
      addSprite(9, 5, portal)
    }
  }, Math.max(4000, 12000 - level * 2000))
}

function nextLevel() {
  level++

  if (level >= 5) {
    clearInterval(spawnLoop)
    clearInterval(moveLoop)
    clearText()
    addText("YOU BEAT ALL LEVELS!", { x: 0, y: 5, color: color`6` })
    gameOver = true
    return
  }

  startLevel()
}

onInput("w", () => { if (!gameOver) getFirst(player).y -= 1 })
onInput("s", () => { if (!gameOver) getFirst(player).y += 1 })
onInput("a", () => { if (!gameOver) getFirst(player).x -= 1 })
onInput("d", () => { if (!gameOver) getFirst(player).x += 1 })

setInterval(() => {
  if (gameOver) return

  if (
    tilesWith(player, block1).length ||
    tilesWith(player, block2).length ||
    tilesWith(player, block3).length ||
    tilesWith(player, block4).length
  ) {
    clearText()
    addText("GAME OVER", { x: 2, y: 5, color: color`3` })
    gameOver = true
    clearInterval(spawnLoop)
    clearInterval(moveLoop)
  }

  if (tilesWith(player, portal).length) {
    nextLevel()
  }

}, 50)

startLevel()