/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

@title: Dodge da demon
@author: 
@tags: []
@addedOn: 2025-00-00
*/

const player = "p"
const demonKey = "d"
const bg = "b"

setLegend(
  [player, bitmap`
........4.......
.......4........
.......4........
......000.......
...0000.0000....
..00.7..7..0....
..0........00...
..000..8.000....
....000000......
.....0..0.......
.....0..0.......
.....0..0.......
....00..00......
................
................
................`],
  [demonKey, bitmap`
................
................
.....333........
....3.3.333.....
33333.33..3.....
.3.00.00.33.....
..30...0333.....
...3....533.....
..33.555..3.....
..3......3......
...3..33.3......
...3.333.3......
...33...33......
........3.......
................
................`],
  [bg, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................`]
)

setBackground(bg)

setMap(map`
................
................
................
................
.......p........
................
................
................
................
......d.........`)

onInput("w", () => {
  getFirst(player).y -= 1;
});

onInput("s", () => {
  getFirst(player).y += 1;
});

onInput("a", () => {
  getFirst(player).x -= 1;
});

onInput("d", () => {
  getFirst(player).x += 1;
});

let over = false
let speed = 600
let timeLeft = 30

let demon = getFirst(demonKey)

let moveDemon = setInterval(() => {
  if (over) return
  let p = getFirst(player)
  if (!p || !demon) return

  let dx = Math.sign(p.x - demon.x)
  let dy = Math.sign(p.y - demon.y)
  demon.x += dx
  demon.y += dy

  if (demon.x === p.x && demon.y === p.y) {
    over = true
    clearText()
    addText("GAME OVER", { y: 6, color: color`3` })
  }
}, speed)

let timer = setInterval(() => {
  if (over) return

  timeLeft -= 1
  clearText()
  addText(`${timeLeft}`, { x: 14, y: 0, color: color`2` })

  if (timeLeft === 0) {
    over = true
    clearInterval(moveDemon)
    clearText()
    addText("YOU WIN!", { y: 6, color: color`4` })
  }

  if (speed > 100) {
    speed -= 15
    clearInterval(moveDemon)
    moveDemon = setInterval(() => {
      if (over) return
      let p = getFirst(player)
      if (!p || !demon) return
      let dx = Math.sign(p.x - demon.x)
      let dy = Math.sign(p.y - demon.y)
      demon.x += dx
      demon.y += dy
      if (demon.x === p.x && demon.y === p.y) {
        over = true
        clearText()
        addText("GAME OVER", { y: 6, color: color`3` })
      }
    }, speed)
  }
}, 1000)