/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started
*/

const player = "p"
const ground = "g"
const bullet = "b"

setLegend(
  [ player, bitmap`
................
................
................
................
................
................
................
................
....3333330.....
...336666330....
...369669630....
..33666666333...
...366999630....
...336666330....
....333333......
......3..3......` ],
  [ ground, bitmap`
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDD`],
  [ bullet, bitmap`
...00.000.00....
....0.000.0.....
....00.0.00.....
......000.......
.......0........
......000.......
.....00000......
.....00000......
.....00000......
.....00000......
.....00000......
......000.......
................
................
................
................`],
)

// setSolids([player, wall])

let level = 0
const levels = [
  map`
.bbbbbbbbbbbb
b.....b..b...
....b........
..b....bb.b..
.............
.............
.............
.............
.............
.......p.....
ggggggggggggg`
]

setMap(levels[level])

setPushables({
  [ player ]: [bullet],
  [ bullet ]: [player],
  
})

onInput("a", () => {
  getFirst(player).x -= 1
  getFirst(bullet).y += 1
})

onInput("d", () => {
  getFirst(player).x += 1
})

afterInput(() => {
  var curr_bullet = getFirst(bullet)
  if (curr_bullet !== undefined){
    curr_bullet.y +=1
  }
  else{
    curr_bullet = getFirst(bullet)
  }
})