/*
@title: Falling Dodge
@author: samar 
@tags: [simple,arcade]
@addedOn: 2025-00-00
*/

const player = "p";
const obstacle = "o";
const background = "b";

setLegend(
  [player, bitmap`
................
................
................
.....00000......
....0.....0.....
....0.0.0.0.....
....0.....0.....
....0.000.0.....
....0.....0.....
.....00000......
.......0........
.....00000......
.......0........
.......0........
......0.0.......
.....0...0......`],
  [obstacle, bitmap`
.......66.......
........6.......
.....66.6.6.....
....66.66.66....
....666666.6....
...6699999966...
...69999999966..
..669999999996..
..669933339996..
..699333333996..
..699333333996..
...69333333996..
...69333333996..
...6993333996...
....66999996....
.....666666.....`],
  [background, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................`]
);

setBackground(background);

setMap(map`
........
........
........
........
........
........
........
...p....`);

let score = 0;

addText(`Score: ${score}`, { x: 0, y: 0, color: color`3` });

onInput("a", () => {
  getFirst(player).x -= 1;
});
onInput("d", () => {
  getFirst(player).x += 1;
});

function spawnObstacle() {
  const x = Math.floor(Math.random() * 8);
  addSprite(x, 0, obstacle);
}
function moveObstacles() {
  const obstacles = getAll(obstacle);
  for (let i = 0; i < obstacles.length; i++) {
    obstacles[i].y += 1;
  }
}
function checkCollision() {
  const p = getFirst(player);
  const obstacles = getAll(obstacle);
  for (let i = 0; i < obstacles.length; i++) {
    if (obstacles[i].x === p.x && obstacles[i].y === p.y) {
      return true;
    }
  }
  return false;
}
const gameInterval = setInterval(() => {
  spawnObstacle();
  moveObstacles();
  if (checkCollision()) {
    clearInterval(gameInterval);
    addText("Game Over!", { x: 2, y: 4, color: color`red` });
  } else {
    score += 1;
    clearText();
    addText(`Score: ${score}`, { x: 0, y: 0, color: color`3` });
  }
}, 1000);
