// 1. Setup our keys as variables
const player = "p";
const apple = "a";

// 2. Legend - Updated the apple bitmap with '4' for a darker color
setLegend(
  [ player, bitmap`
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .00000000000000.
    .0............0.
    .00000000000000.
  ` ],
  [ apple, bitmap`
    ................
    ......44........
    .....4444.......
    ....444444......
    ....444444......
    .....4444.......
    ......44........
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
  ` ]
);

// 3. Map - Create the game grid (20x15 tiles)
setMap(map`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
.........p..........
`);

// 4. Game State Variables
let score = 0;

// 5. Player Movement Controls
// Move Left
onInput("a", () => {
  let p = getFirst(player);
  if (p && p.x > 0) {
    p.x = p.x - 1;
  }
});

// Move Right
onInput("d", () => {
  let p = getFirst(player);
  if (p && p.x < 19) { 
    p.x = p.x + 1;
  }
});

// 6. Game Loop (Spawning and Falling Logic)
setInterval(() => {
  // Randomly spawn an apple at the top row (y = 0)
  if (Math.random() < 0.3) { 
    let randomX = Math.floor(Math.random() * 20);
    if (getTile(randomX, 0).length === 0) {
      addSprite(randomX, 0, apple);
    }
  }

  // Move all existing apples down
  let apples = getAll(apple);
  for (let i = 0; i < apples.length; i++) {
    let currentApple = apples[i];
    let nextY = currentApple.y + 1;
    let p = getFirst(player);

    // Check for collision with the player/basket
    if (p && currentApple.x === p.x && nextY === p.y) {
      score = score + 1;
      clearText();
      addText("Score: " + score, { x: 1, y: 1 });
      currentApple.remove();
    } 
    // Check if apple hits the bottom floor
    else if (nextY >= 15) {
      currentApple.remove(); 
    } 
    // Otherwise, just move it down
    else {
      currentApple.y = nextY;
    }
  }

}, 200);