/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

@title: horse rider 1
@author: mozes
@tags: []
@addedOn: 2025-12-05
*/

const player = "p"
const fence = "f"
const jumpgate = "j"

setLegend(
  [player, bitmap`
.....6666.......
......CCC.......
......CC0.......
......CCC.......
......7575......
......755.5.FFF.
......77555FF0C.
......7775FFCCCC
..CCCC555FFCCCC.
FFCCCC555CCCC...
FFCCCC555CCCC...
FCCCCCLLLCCC....
F.CCCCCCCCCC....
F...CC..CCC.....
...C.C..C.C.....
...C.C.C..C.....`],
  [fence, bitmap`
................
................
................
................
................
................
................
................
CCCCCCCCCCCCCCCC
C..............C
CCCCCCCCCCCCCCCC
C..............C
CCCCCCCCCCCCCCCC
C..............C
CCCCCCCCCCCCCCCC
C..............C`],
  [jumpgate, bitmap`
................
.......333......
.......232......
.......333......
.......232......
.......333......
.......232......
.......333......
.......232......
.......333......
.......232......
.......333......
.......232......
.......333......
.......232......
.......333......`]
)

setSolids([fence, jumpgate, player])

let level = 0
const levels = [
  map`
.j........f.........
......j......j..f...
..f...............j.
.....f....f.........
..j............f....
.....j.....j......j.
.....j..f...........
p.j.f..........f....
......j....f........
.........j........j.
.f.....f............
....j.....f.........
.................f..
...f...........j....
.j....f..f..f.....j.
....................`
]

setMap(levels[level])

setPushables({
  [player]: [],
})

onInput("s", () => {
  getFirst(player).y += 1
});

onInput("w", () => {
  getFirst(player).y -= 1
});

onInput("d", () => {
  getFirst(player).x += 1
});

onInput("a", () => {
  getFirst(player).x -= 1
});

onInput("j", () => {
  getFirst(player).x -= 2
});

onInput("l", () => {
  getFirst(player).x += 2
});

onInput("i", () => {
  getFirst(player).y -= 2
});

onInput("k", () => {
  getFirst(player).y += 2
})