/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

@title: lock rooms
@author: sapugaming
@tags: [lock, rooms]
@addedOn: 2025-00-00
*/

const player = "p";
const key = "k";
const vertical = "v";
const horizontal = "h";

const door = "d";
const portal = "o";

const side1 = "s";
const side2 = "w";

setLegend(
  [ player, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
........0.0.....
......77272.....
.....7777777....
....77777733....`],
  [ key, bitmap`
................
................
................
................
................
................
.....666........
.....69666666...
.....6966.66....
.....666........
................
................
................
................
................
................`],
  [ door, bitmap`
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......
......CCCC......`],
  [ portal, bitmap`
................
................
................
......HHHHH.....
....HHH5555HH...
...HH8858855H...
...HH81888355H..
..HHH88666335H..
..H88686666335H.
..H18188666335H.
..H1H168755555H.
..HH1657755777H.
....HH555557HH..
......HHHHHHH...
................
................`],
  [ vertical, bitmap`
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......`],
  [ horizontal, bitmap`
................
................
................
................
................
................
LLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLL
................
................
................
................
................
................
................`],
  [ side1, bitmap`
................
................
................
................
................
................
.......LLLLLLLLL
.......LLLLLLLLL
.......LLLLLLLLL
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......`],
  [ side2, bitmap`
................
................
................
................
................
................
LLLLLLLLLL......
LLLLLLLLLL......
LLLLLLLLLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......
.......LLL......`],
)

setSolids([player, vertical, horizontal], side1, side2, door)

let level = 0
const levels = [
  map`
.k......
........
..shhhw.
..vo..v.
.pv...v.
..v...d.`
]

setMap(levels[level])

setPushables({
  [ player ]: []
})

//movements
onInput("s", () => {
  getFirst(player).y += 1
})

onInput("d", () => {
  getFirst(player).x += 1
})

onInput("w", () => {
  getFirst(player).y -= 1
})

onInput("a", () => {
  getFirst(player).x -= 1
})

afterInput(() => {
  let inventory = 0;
  
  const getKey = tilesWith(key, plater).length;
  const doorUnlock = tilesWith(door, player).

  if getKey {
    inventory = 1;
  }
  
})