/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

/*
@title: loto
@author: ixel
@tags: []
@addedOn: 2025-00-00
*/

const player = "p"
const obstacle = "o"

setLegend(
  [ player, bitmap`
................
................
.......000......
.......0.0......
......0..0......
......0...0.0...
....0003.30.0...
....0.0...000...
....0.05550.....
......0...0.....
.....0....0.....
.....0...0......
......000.......
......0.0.......
.....00.00......
................` ],
  [ obstacle, bitmap`
................
................
................
................
................
................
....22222222....
....32222322....
....22232222....
....22222222....
....22222223....
....22222222....
....22222222....
....22222222....
................
................` ]
)

setSolids([])

let level = 0
const levels = [
  map`
p.............
..............
..............
..............
..............
..............
..............
..............
..............
..............`
]

setMap(levels[level])

let lives = 3
let gameOver = false

// Movement
onInput("w", () => { getFirst(player).y -= 1 })
onInput("s", () => { getFirst(player).y += 1 })
onInput("a", () => { getFirst(player).x -= 1 })
onInput("d", () => { getFirst(player).x += 1 })

// Spawn obstacles
setInterval(() => {
  if (gameOver) return
  
  let x = Math.floor(Math.random() * width())
  addSprite(x, 0, obstacle)
}, 800)

// Move obstacles down
setInterval(() => {
  if (gameOver) return
  
  getAll(obstacle).forEach(o => {
    o.y += 1
    
    // Remove if off screen
    if (o.y >= height()) {
      o.remove()
    }
    
    // Collision detection
    if (o.x === getFirst(player).x && o.y === getFirst(player).y) {
      lives -= 1
      o.remove()
      
      if (lives <= 2) {
        gameOver = true
        clearText()
        addText("GAME OVER", { x: 3, y: 5, color: color`3` })
      }
    }
  })
}, 300)