/*
@title: monster battle
@author: shadee
*/


const player = "p";
const monster = "g";

setLegend(
  [ player, bitmap`
................
.....8888...7...
....88...8..7...
....88...8..7...
.....8888...7...
......888...7...
......8...77777.
.....88888..7...
.....88..8887...
....888.....7...
...88.8....7....
..8...88........
.....8.8........
....8...88......
....8....8......
...8............`],
  [ monster, bitmap`
................
................
................
....444444......
...44....44.....
...4......4.....
...4.......4....
...4.......4....
...4.......4....
...44......4....
....4......4....
....44....44....
.....444444.....
................
................
................`]
);

let level = 0;
let playerHealth = 10;
let monsterHealth = 5;
const levels = [
  map`
p.g`
];

const currentLevel = levels[level];
setMap(currentLevel);

setSolids([player,monster]);

setPushables({
  [player]: []
});

// START - PLAYER MOVEMENT CONTROLS

onInput("d", () => {
  getFirst(player).x += 1;
});
onInput("a", () => {
  getFirst(player).x -= 1;
});
onInput("l", () => {
  monsterHealth = monsterHealth - 1;
  playerHealth = playerHealth -1;
});


// END - PLAYER MOVEMENT CONTROLS

afterInput(() => {
  if (monsterHealth === 0) {
    // increase the current level number
    level = level + 1;

    const currentLevel = levels[level];

    // make sure the level exists and if so set the map
    if (currentLevel !== undefined) {
      setMap(currentLevel);
    } else {
      addText("you win!", { y: 4, color: [255, 0, 0] });
    }
  }
});
