
/* 
@title: maze_game_starter
@description: A simple template to help you get started with making a maze game.
@author: Cheru Berhanu
@tags: []
@addedOn: 2023-08-08
*/

    const player = "p";
    const wall = "w";
    const goal = "g";
    const key = "k";
    const lock = "l";
    const box = "b";
    const enemy = "e";
    const redPortal = "R";
    const bluePortal = "B";
    const fragile = "f";
    const broken = "s";
    const npc = "n"; 
    const greenPortal = "G";
    const yellowPortal = "Y";


setLegend(
	[ player, bitmap`
................
................
................
................
....33333333....
....33333333....
....33333333....
....33033033....
....33333333....
....33333333....
....33333333....
....33333333....
................
................
................
................` ],
    [ wall, bitmap`
0000000000000000
0..............0
0..............0
0..............0
0..............0
0..............0
0..............0
0000000000000000
0000000000000000
0......00......0
0......00......0
0......00......0
0......00......0
0......00......0
0......00......0
0000000000000000` ],
    [ goal, bitmap`
................
................
.......44444....
.......4....4...
.......4.....4..
.......4444..4..
.......4...44...
.......4........
.......4........
.......4........
.......4........
.......4........
.......4........
.....44444......
................
................` ],
    [ key, bitmap`
................
................
................
................
................
................
....66......6...
...6..6...6.6...
...6..6...6.6...
...6..66666666..
...6..6.........
....66..........
................
................
................
................` ],
    [ lock, bitmap`
0000000000000000
0..............0
0..............0
0..............0
0......6.......0
0.....6.6......0
0.....6.6......0
0....66666.....0
0....6...6.....0
0....6.6.6.....0
0....6.6.6.....0
0....6...6.....0
0.....666......0
0..............0
0..............0
0000000000000000` ],
    [ box, bitmap`
9999999999999999
99............99
9.9..........9.9
9..9........9..9
9...9......9...9
9....9....9....9
9.....9..9.....9
9......99......9
9......99......9
9.....9..9.....9
9....9....9....9
9...9......9...9
9..9........9..9
9.9..........9.9
99............99
9999999999999999` ],
    [ enemy, bitmap`
................
................
.....555555.....
...5555555555...
...5535555355...
..555535535555..
..555533335555..
..555555555555..
..555555555555..
..555555555555..
..555555555555..
...5555555555...
...5555555555...
.....555555.....
................
................` ],
    [ redPortal, bitmap`
................
.....333333.....
....33....33....
...33......33...
...3....3...3...
...3...33...3...
...3....3...3...
...3....3...3...
...3....3...3...
...3...333..3...
...3........3...
...33......33...
....33....33....
.....333333.....
................
..333333333333..` ],
    [ bluePortal, bitmap`
................
.....777777.....
....77....77....
...77......77...
...7....7...7...
...7...77...7...
...7....7...7...
...7....7...7...
...7....7...7...
...7...777..7...
...7........7...
...77......77...
....77....77....
.....777777.....
................
..777777777777..` ],
    [ fragile, bitmap`
...L.......L....
....L.....L.....
....L....L......
.L...L...L......
..LL.L..LL......
....LLLL.L......
......LLL..LLL..
......LLLLL.....
...LLLL.LL......
LLL.L..LL.LL....
...L...L.L..LL..
...L...L.L....L.
..L....L..L.....
.L....L...L.....
......L....L....
................` ],
    [ broken, bitmap`
.....L....L.....
..L..L....L...L.
...L.LLLLLL.LL..
...LL000000LL...
...L00000000L.L.
..L0000000000L..
.LL0000000000L..
..L0000000000L..
..L0000000000L..
..L0000000000L..
..L0000000000LL.
.LLL00000000L...
L..LL000000LL...
....LLLLLLL..L..
...L.L..L.....L.
..L.....L......L` ],
    [ npc, bitmap`
................
................
................
................
....44444444....
....44444444....
....44444444....
....40044004....
....44444444....
....44444444....
....44444444....
....44444444....
................
................
................
................` ],
    [ greenPortal, bitmap`
................
.....DDDDDD.....
....DD....DD....
...DD......DD...
...D........D...
...D...DD...D...
...D..D..D..D...
...D....D...D...
...D...D....D...
...D..DDDD..D...
...D........D...
...DD......DD...
....DD....DD....
.....DDDDDD.....
................
..DDDDDDDDDDDD..` ],
    [ yellowPortal, bitmap`
................
.....666666.....
....66....66....
...66......66...
...6........6...
...6...66...6...
...6..6..6..6...
...6....6...6...
...6...6....6...
...6..6666..6...
...6........6...
...66......66...
....66....66....
.....666666.....
................
..666666666666..` ]
)

setSolids([ player, wall, lock, box, npc ])

let level = 0;
const levels = [
  map`
.....
.....
p...g
.....
.....`,
  map`
pw...
.w.w.
.w.w.
.w.w.
...wg`,
  map`
gw...w..
...w.w.w
wwww.w.w
p.w.....
w.wwwww.
w...w...
w.www.ww
........`, 
  map`
.pwwwwk
.ww....
.w..www
.w.ww..
.w..w.g
.ww.w..
....l..`,
  map`
www...k
....www
.wwww..
....l.g
.wwww..
....www
www...p`, 
  map`
gwwwww.
.w.....
.w.wwwb
.wbwpw.
...w.w.
ww.w.w.
bwww...`,
  map`
b..wwwwww
...wwwwww
...bww..w
...b....w
p..bwww.g
...b....w
...bww..w
...wwwwww
b..wwwwww`,
  map`
.wwww.b..
......w..
bwwwwwwwl
....w....
.p...e..g
....w....
.wwwwwwww
.w..b....
....bb..k`,
  map`
.....w...
k.we.w.p.
www..wwwb
..w....w.
g.l..e...
..w....w.
wwwe.www.
.....w.e.
.....w...`,
  map`
...b..w.....
.www..w.www.
..pwb...wR..
.www.w..www.
.....w......
wwwwwwwwwwww
......w.....
.www..w.www.
..gw...bwB..
.www.w..www.
.....w..b...`, 
  map`
w..f..k
...ff..
..wwwww
p..s.g.
..wwwwl
....f..
w..f...`, 
  map`
pw.....w...wR..
.w.www.www.www.
.w...w.....f...
...www.www.wwww
.www....w......
..f..wwf..www.w
.ww.wwwlw.w...w
..w...wgw.w.www
wwwww.w.www....
......w.e.w..w.
.wfwwwwww.ww.w.
.w......w....w.
.w.www.wwwwfww.
ww.wBw.w.....w.
.....w...w.w.wk`,
  map`
......wsfffsfsf
......wessfffsf
wwwwwwwsssfsfsf
ws....wsfffsfff
w..w.bwssfsssfs
wg.w.blp.fsfffs
w..w.bwsfssfsss
ws....wffsffffs
wwwwwwwfssssskf
......wfsfffssf
......wfffsffff`,
  map`
gw..w...
.wb...w.
..lwwww.
w.n.p...
ww.wwww.
k.w...w.
w...w...`,
  map`
wwwwwwwwwwwww
w...w.......w
w...l.......w
w...www..wwww
wnewwkw.....w
...e..w.....w
.g.e..wwww..w
...e........w
wwww........w
w...wwwwww..w
w...b.......w
wpw.........w
w.wwwwwwwwwww`,
  map`
wwwwwwwwwww
R.........p
...........
wwlwwwewwwe
...w.B.w.Y.
...w...w...
...w...w...
.G.w.k.w.g.`,
  map`
...wwwwwwwww...
.R.wwwwwwwww.B.
...wwwwwwwww...
k..fl......wffw
wwnww.........w
...w..........w
...w.......wwww
.g.w...p..ww...
wwww.......f...
w.........ww...
w.........ww...
wfwwwwwwwwww.b.
w..e...e...w...
w..e.e.e.G.w.Y.
w....e.....w...`
]

setMap(levels[level])

setPushables({
    [ player ]: [ box ],
    [ box ]: [ box ],
    [ box ]: [ npc ]
})

onInput("j", () => {
  setMap(levels[level])
})

onInput("d", () => {
  // Move the player one tile to the right
  getFirst(player).x += 1
})

onInput("a", () => {
  // Move the player one tile to the left
  getFirst(player).x += -1
})

onInput("s", () => {
	getFirst(player).y += 1
})

onInput("w", () => {
	getFirst(player).y += -1
})

// Track previous position (must be let, not const)
let previousX = getFirst(player).x;
let previousY = getFirst(player).y

afterInput(() => {
  const goalsCovered = tilesWith(player, goal); // concat combines two arrays
  const keysTaken = tilesWith(player, key); // ADDED: all the keys that the player is on
  const enemiesCovered = tilesWith(player, enemy); // ADDED: tiles with players on enemies
  const redPortalsCovered = tilesWith(player, redPortal);
  const bluePortalsCovered = tilesWith(player, bluePortal);
  const playerSprite = getFirst(player);
  const brokenCovered = tilesWith(player, broken);
  const greenPortalsCovered = tilesWith(player, greenPortal);
  const yellowPortalsCovered = tilesWith(player, yellowPortal);
  
// there is one player, so if 1 or more tiles with both a goal and a player, next level
if (goalsCovered.length >= 1) {
// increase the current level number
level = level + 1;

    const currentLevel = levels[level];

    // make sure the level exists and if so set the map
    // otherwise, we have finished the last level, there is no level
    // after the last level
    if (currentLevel !== undefined) {
      setMap(currentLevel);
    } else {
            addText("Congrats! You win!", { y: 4, color: color`4` });
        }

}

// ADDED: remove the lock and key if the key is picked up
if (keysTaken.length >= 1) {
getFirst(lock).remove();
getFirst(key).remove();
}

// ADDED: if any player is on an enemy, they lose
    if (enemiesCovered.length > 0) {
        setMap(levels[level])
    }

 if (redPortalsCovered.length >= 1) {
    const bp = getFirst(bluePortal);
    const pl = getFirst(player);

    // teleport player to blue portal
    pl.x = bp.x;
    pl.y = bp.y;
  }
  
  // ADDED: teleport the player to the red portal if they are standing on the blue one
  if (bluePortalsCovered.length >= 1) {
    const rp = getFirst(redPortal);
    const pl = getFirst(player);

    // teleport player to red portal
    pl.x = rp.x;
    pl.y = rp.y;
  }

// Check if the previous tile had a fragile tile on it
  const previousTileSprites = getTile(previousX, previousY);

  previousTileSprites.forEach(sprite => {
    if (sprite.type === fragile) {
      sprite.type = broken; // turn fragile into broken
    }
  });

  // If player is standing on a broken tile → lose
  if (brokenCovered.length >= 1) {
    setMap(levels[level]);
  }

  // Update previous position AFTER processing
  previousX = playerSprite.x;
  previousY = playerSprite.y;

  if (greenPortalsCovered.length >= 1) {
    const yp = getFirst(yellowPortal);
    const pl = getFirst(player);

    // teleport player to yellow portal
    pl.x = yp.x;
    pl.y = yp.y;
  }
  
  // ADDED: teleport the player to the green portal if they are standing on the yellow one
  if (yellowPortalsCovered.length >= 1) {
    const gp = getFirst(greenPortal);
    const pl = getFirst(player);

    // teleport player to green portal
    pl.x = gp.x;
    pl.y = gp.y;
  }
  
});

