// 1. Définition des éléments
const player = "p";
const goal = "g";

// Graphisme du joueur et de la pièce
setLegend(
  [ player, bitmap`
................
.....000000.....
....0FFFFFF0....
...0F0FFFF0F0...
...0FFFFFFFF0...
...0F00FF00F0...
...0F00FF00F0...
...0FFFFFFFF0...
....0FFFFFF0....
.....000000.....
....00....00....
...00......00...
...00......00...
....00....00....
.....000000.....
................` ],
  
  [ goal, bitmap`
................
.....333330.....
...3333333330...
..333.....3330..
..33...3...330..
.33...333...330.
.33...333...330.
.33...333...330.
.33...333...330.
.33...333...330.
..33...3...330..
..333.....3330..
...3333333330...
.....333330.....
................
................` ]
);

// 2. Taille de la carte (10x10)
const MAP_WIDTH = 10;
const MAP_HEIGHT = 10;

setMap(map`
..........
.p........
..........
..........
..........
..........
..........
..........
..........
........g.
`);

// Variable pour gérer le score
let score = 0;

// Function pour faire apparaître la pièce à un endroit aléatoire
function respawnGoal() {
  const g = getFirst(goal);
  // Génère de nouvelles coordonnées entre 0 et 9
  g.x = Math.floor(Math.random() * MAP_WIDTH);
  g.y = Math.floor(Math.random() * MAP_HEIGHT);
}

// 3. Déplacements (Z, Q, S, D ou W, A, S, D + Flèches)
onInput("w", () => { getFirst(player).y -= 1; });
onInput("s", () => { getFirst(player).y += 1; });
onInput("a", () => { getFirst(player).x -= 1; });
onInput("d", () => { getFirst(player).x += 1; });

onInput("i", () => { getFirst(player).y -= 1; });
onInput("k", () => { getFirst(player).y += 1; });
onInput("j", () => { getFirst(player).x -= 1; });
onInput("l", () => { getFirst(player).x += 1; });

// 4. Boucle de jeu : Vérification de la collision et mise à jour du score
afterInput(() => {
  const p = getFirst(player);
  const g = getFirst(goal);
  
  // Si le joueur touche la pièce
  if (p.x === g.x && p.y === g.y) {
    score += 1; // On augmente le score
    respawnGoal(); // La pièce réapparaît ailleurs
  }
  
  // Affichage du score en haut à gauche
  clearText();
  addText(`Score: ${score}`, { x: 1, y: 1, color: color`3` });
});