const PLAYER = "p"
const APPLE = "a"
const ORANGE = "o"

let choice = ""

setLegend(
  [PLAYER, bitmap`
................
.......33.......
......3333......
.......33.......
......3333......
.....333333.....
....33333333....
.......33.......
......3..3......
.....33..33.....
................
................
................
................
................
................`],

  [APPLE, bitmap`
.......3........
......33........
.....3333.......
....333333......
...33333333.....
...33333333.....
...33333333.....
....333333......
.....3333.......
......33........
................
................
................
................
................
................`],

  [ORANGE, bitmap`
................
................
.......3........
.....33333......
....3333333.....
...33333333.....
...33333333.....
...33333333.....
....3333333.....
.....33333......
................
................
................
................
................
................`]
)

setMap(map`
........
........
........
...p....
........
.a....o.
........
........`)

function checkChoice() {
  let player = getFirst(PLAYER)

  if (player.x === 1 && player.y === 5) {
    choice = "APPLE"
    showChoice()
  }

  if (player.x === 6 && player.y === 5) {
    choice = "ORANGE"
    showChoice()
  }
}

function showChoice() {
  clearText()

  addText("You chose:", {
    x: 4,
    y: 1,
    color: color`3`
  })

  addText(choice, {
    x: 4,
    y: 3,
    color: color`3`
  })
}

onInput("w", () => {
  getFirst(PLAYER).y -= 1
  checkChoice()
})

onInput("s", () => {
  getFirst(PLAYER).y += 1
  checkChoice()
})

onInput("a", () => {
  getFirst(PLAYER).x -= 1
  checkChoice()
})

onInput("d", () => {
  getFirst(PLAYER).x += 1
  checkChoice()
})

addText("Choose!", {
  x: 6,
  y: 0,
  color: color`3`
})