/*
@title: Ping Pong
@author: YourName
*/

const paddleLeft = "l";
const paddleRight = "r";
const ball = "b";

setLegend(
  [ paddleLeft, bitmap`
......202.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......202.......`],
  [ paddleRight, bitmap`
......202.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......202.......`],
  [ ball, bitmap`
................
................
.......33333....
......3333333...
.....333333333..
.....333333333..
.....333333333..
.....333333333..
.....333333333..
.....333333333..
......3333333...
.......33333....
................
................
................
................`]
);

setSolids([paddleLeft, paddleRight]);

let ballX = 8;
let ballY = 8;
let ballDX = 1;
let ballDY = 1;
let leftPaddleY = 7;
let rightPaddleY = 7;
const paddleHeight = 3;

const leftPaddleX = 1;
const rightPaddleX = 15;

const court = map`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................`;

setMap(court);

function drawPaddles() {
  clearTile(leftPaddleX, leftPaddleY);
  clearTile(leftPaddleX, leftPaddleY + 1);
  clearTile(leftPaddleX, leftPaddleY + 2);
  addSprite(leftPaddleX, leftPaddleY, paddleLeft);
  addSprite(leftPaddleX, leftPaddleY + 1, paddleLeft);
  addSprite(leftPaddleX, leftPaddleY + 2, paddleLeft);
  
  clearTile(rightPaddleX, rightPaddleY);
  clearTile(rightPaddleX, rightPaddleY + 1);
  clearTile(rightPaddleX, rightPaddleY + 2);
  addSprite(rightPaddleX, rightPaddleY, paddleRight);
  addSprite(rightPaddleX, rightPaddleY + 1, paddleRight);
  addSprite(rightPaddleX, rightPaddleY + 2, paddleRight);
}

function moveBall() {
  clearTile(ballX, ballY);
  ballX += ballDX;
  ballY += ballDY;
  if (ballY < 0 || ballY > 15) ballDY *= -1;

  if (ballX === leftPaddleX + 1 && ballY >= leftPaddleY && ballY <= leftPaddleY + 2) {
    ballDX *= -1;
  }
  if (ballX === rightPaddleX - 1 && ballY >= rightPaddleY && ballY <= rightPaddleY + 2) {
    ballDX *= -1;
  }

  if (ballX < 0 || ballX > 15) {
    ballX = 8;
    ballY = 8;
    ballDX = Math.random() < 0.5 ? 1 : -1;
    ballDY = Math.random() < 0.5 ? 1 : -1;
  }

  addSprite(ballX, ballY, ball);
}

onInput("w", () => {
  if (leftPaddleY > 0) leftPaddleY -= 1;
  drawPaddles();
});

onInput("s", () => {
  if (leftPaddleY < 13) leftPaddleY += 1;
  drawPaddles();
});

onInput("i", () => {
  if (rightPaddleY > 0) rightPaddleY -= 1;
  drawPaddles();
});

onInput("k", () => {
  if (rightPaddleY < 13) rightPaddleY += 1;
  drawPaddles();
});

setInterval(() => {
  moveBall();
}, 200);

drawPaddles();
