const player = 'p';
const bot = 'b';
const tree = 't';
const boulder = 'o';
const ground = 'g';

setLegend(
  [player, bitmap`
................
................
................
................
.....888888.....
....88888888....
....88888888....
.....888888.....
.....888888.....
....88888888....
....88888888....
.....888888.....
................
................
................
................`],
  [bot, bitmap`
................
................
................
................
.....FFFFFF.....
....FFFFFFFF....
....FFFFFFFF....
.....FFFFFF.....
.....FFFFFF.....
....FFFFFFFF....
....FFFFFFFF....
.....FFFFFF.....
................
................
................
................`],
  [tree, bitmap`
.......0........
......000.......
.....00000......
....0000000.....
....0000000.....
.....00000......
......000.......
.......0........
.......0........
.......0........
......000.......
.....00000......
....0000000.....
.......0........
.......0........
.......0........`],
  [boulder, bitmap`
................
....00000000....
...0000000000...
..000000000000..
..000000000000..
.00000000000000.
.00000000000000.
.00000000000000.
.00000000000000.
.00000000000000.
..000000000000..
..000000000000..
...0000000000...
....00000000....
................
................`],
  [ground, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................`]
);

const levels = [
  map`
..t....o..
.o...t....
..o.......
...t..o...
.t.....t..
..o...o...
.t...t...o
...o...t..
..t...p.b.
...t...o..`,
];

let currentRound = 1;
let isTagger = false;

setBackground(ground);
setMap(levels[0]);

getFirst(player).x = 4;
getFirst(player).y = 8;
getFirst(bot).x = 5;
getFirst(bot).y = 8;

function startRound() {
  isTagger = false;
  setTimeout(() => {
    isTagger = true;
  }, 5000);
}
startRound();

onInput("w", () => { if (!tileHasObject(getFirst(player).x, getFirst(player).y - 1)) getFirst(player).y -= 1; });
onInput("a", () => { if (!tileHasObject(getFirst(player).x - 1, getFirst(player).y)) getFirst(player).x -= 1; });
onInput("s", () => { if (!tileHasObject(getFirst(player).x, getFirst(player).y + 1)) getFirst(player).y += 1; });
onInput("d", () => { if (!tileHasObject(getFirst(player).x + 1, getFirst(player).y)) getFirst(player).x += 1; });

function tileHasObject(x, y) {
  let objects = tilesWith(tree, boulder).filter(t => t.x === x && t.y === y);
  return objects.length > 0;
}

function botMovement() {
  if (!isTagger) return;
  let botSprite = getFirst(bot);
  let playerSprite = getFirst(player);

  if (botSprite.x < playerSprite.x && !tileHasObject(botSprite.x + 1, botSprite.y)) botSprite.x++;
  else if (botSprite.x > playerSprite.x && !tileHasObject(botSprite.x - 1, botSprite.y)) botSprite.x--;
  if (botSprite.y < playerSprite.y && !tileHasObject(botSprite.x, botSprite.y + 1)) botSprite.y++;
  else if (botSprite.y > playerSprite.y && !tileHasObject(botSprite.x, botSprite.y - 1)) botSprite.y--;
}
setInterval(botMovement, 500);

afterInput(() => {
  if (tilesWith(player, bot).length > 0) {
    clearText();
    addText("YOU'RE TAGGED!", { x: 5, y: 1, color: color`3` });
    isTagger = !isTagger;
    currentRound++;
    if (currentRound > 3) {
      clearText();
      addText("GAME OVER!", { x: 5, y: 3, color: color`2` });
      currentRound = 1;
    }
  }
});

