/*
@title: Arrow Reflex
@author: Adrian
@tags: reflex, arcade
@addedOn: 2026.01.04
*/

const UP = "U"
const DOWN = "D"
const LEFT = "L"
const RIGHT = "R"

setLegend(
  [UP, bitmap`
................
.......0........
......000.......
.....00000......
....0000000.....
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......`],

  [DOWN, bitmap`
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
......000.......
....0000000.....
.....00000......
......000.......
.......0........
................
................`],

  [LEFT, bitmap`
................
................
................
................
....0...........
...00...........
..00000000000000
.000000000000000
..00000000000000
...00...........
....0...........
................
................
................
................
................`],

  [RIGHT, bitmap`
................
................
................
................
................
..........0.....
..........00....
0000000000000...
00000000000000..
0000000000000...
..........00....
..........0.....
................
................
................
................`]
)

setMap(map`
.....
.....
..U..
.....
.....`)

let score = 0
let currentArrow = UP
let gameOver = false

function randomArrow() {
  return [UP, DOWN, LEFT, RIGHT][Math.floor(Math.random() * 4)]
}

function spawnArrow() {
  clearText()
  getAll().forEach(s => s.remove())

  currentArrow = randomArrow()
  addSprite(2, 2, currentArrow)
  addText("Score: " + score, { x: 1, y: 1 })
}

function endGame() {
  gameOver = true
  clearText()
  addText("GAME OVER", { x: 4, y: 6 })
  addText("FINAL SCORE", { x: 3, y: 8 })
  addText("" + score, { x: 7, y: 10 })
}

onInput("w", () => {
  if (gameOver) return
  currentArrow === UP ? (score++, spawnArrow()) : endGame()
})

onInput("s", () => {
  if (gameOver) return
  currentArrow === DOWN ? (score++, spawnArrow()) : endGame()
})

onInput("a", () => {
  if (gameOver) return
  currentArrow === LEFT ? (score++, spawnArrow()) : endGame()
})

onInput("d", () => {
  if (gameOver) return
  currentArrow === RIGHT ? (score++, spawnArrow()) : endGame()
})

spawnArrow()
