// /*
// First time? Check out the tutorial game:
// https://sprig.hackclub.com/gallery/getting_started

// @title: Rusher
// @author: 
// @tags: []
// @addedOn: 2025-00-00
// */


const player = "p"
const laser = "l"
const goal = "g"

setLegend(
  [ player, bitmap`
................
................
......0000......
.....0....0.....
.....0.00.0.....
.....0....0.....
......0000......
................
................
................
................
................
................
................
................
................` ],

  [ laser, bitmap`
................
................
3333333333333333
3333333333333333
................
................
3333333333333333
3333333333333333
................
................
................
................
................
................
................
................` ],

  [ goal, bitmap`
................
................
.....444444.....
....4......4....
....4.4444.4....
....4......4....
.....444444.....
................
................
................
................
................
................
................
................
................` ]
)

setSolids([player])

let level = 0

const levels = [
  map`
p........
.........
..l......
.........
......l..
.........
.......g.`,
  
  map`
p........
..l......
.........
.....l...
.........
...l.....
.......g.`,
]

setMap(levels[level])

// Movement
onInput("w", () => getFirst(player).y -= 1)
onInput("s", () => getFirst(player).y += 1)
onInput("a", () => getFirst(player).x -= 1)
onInput("d", () => getFirst(player).x += 1)

// Laser movement loop
setInterval(() => {
  const lasers = getAll(laser)
  
  lasers.forEach(l => {
    l.x += 1
    
    if (l.x > width() - 1) {
      l.x = 0
    }
  })
}, 300)

// Game logic
afterInput(() => {
  const p = getFirst(player)

  // Lose condition
  const lasers = getAll(laser)
  lasers.forEach(l => {
    if (l.x === p.x && l.y === p.y) {
      setMap(levels[level]) // reset
    }
  })

  // Win condition
  const g = getFirst(goal)
  if (p.x === g.x && p.y === g.y) {
    level++
    
    if (level < levels.length) {
      setMap(levels[level])
    } else {
      addText("YOU WIN!", { y: 5, color: color`4` })
    }
  }
})