const cursor = "c"; 
const target = "t"; 
const pixel  = "p"; 
const wall   = "w"; 
const grid   = "g"; 

setLegend(
  [cursor, bitmap`
................
................
................
.......22.......
......2222......
.....222222.....
......2222......
.......22.......
................
................
................
................
................
................
................
................`],

  [target, bitmap`
................
......5555......
.....5....5.....
....5..55..5....
....5..55..5....
.....5....5.....
......5555......
................
................
................
................
................
................
................
................
................`],

  [pixel, bitmap`
................
................
................
.......33.......
.......33.......
................
................
................
................
................
................
................
................
................
................
................`],

  [wall, bitmap`
LLLLLLLLLLLLLLLL
L..............L
L..LLLLLLLLLL..L
L..L........L..L
L..L........L..L
L..L........L..L
L..L........L..L
L..L........L..L
L..L........L..L
L..L........L..L
L..L........L..L
L..L........L..L
L..L........L..L
L..LLLLLLLLLL..L
L..............L
LLLLLLLLLLLLLLLL`],

  [grid, bitmap`
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
0000000000000001
1111111111111111`]
);

setBackground(grid);

let rise = 0; 
let run = 1;  
let calculating = false; 
let level = 0;

const levels = [
  map`
................
................
................
.......t........
................
................
................
................
........c.......
................
................
................
................
................
................
................`,

  map`
................
................
................
................
................
................
...........t....
................
................
...c............
................
................
................
................
................
................`,

  map`
.t..............
................
................
................
................
................
................
................
................
................
................
................
................
................
..............c.
................`
];

const sfxBlip = tune`180: C6-20`;
const sfxGraph = tune`180: C3-20 C4-20`;
const sfxWin = tune`150: C5-100 E5-100 G5-200`;
const sfxFail = tune`150: C2-200`;

function startLevel(idx) {
  if (idx >= levels.length) {
    clearText();
    addText("CALCULATION COMPLETE", { x: 2, y: 7, color: color`3` });
    return;
  }
  
  level = idx;
  setMap(levels[idx]);
  
  rise = 0;
  run = 1;
  calculating = false;
  
  updateScreen();
}

function updateScreen() {
  clearText();
  addText(`RISE ${rise}`, { x: 1, y: 1, color: color`3` });
  addText(`RUN  ${run}`, { x: 9, y: 1, color: color`5` });
  addText(`PRESS J`, { x: 5, y: 14, color: color`7` });
}

startLevel(0);

onInput("w", () => { 
  if(calculating) return;
  rise += 1; 
  playTune(sfxBlip); 
  updateScreen(); 
});

onInput("s", () => { 
  if(calculating) return;
  rise -= 1; 
  playTune(sfxBlip); 
  updateScreen(); 
});

onInput("d", () => { 
  if(calculating) return;
  run += 1; 
  playTune(sfxBlip); 
  updateScreen(); 
});

onInput("a", () => { 
  if(calculating) return;
  run -= 1; 
  playTune(sfxBlip); 
  updateScreen(); 
});

onInput("j", () => {
  if (calculating) return; 
  
  calculating = true;
  playTune(sfxGraph);
  
  const origin = getFirst(cursor);
  if (!origin) return;

  let currentX = origin.x;
  let currentY = origin.y;
  
  const graphInterval = setInterval(() => {
    
    currentX += run;
    currentY -= rise; 
    
    if (currentX < 0 || currentX > 15 || currentY < 0 || currentY > 15) {
      clearInterval(graphInterval);
      failGraph();
      return;
    }

    const tile = getTile(currentX, currentY);
    if (tile.some(t => t.type === wall)) {
      clearInterval(graphInterval);
      failGraph();
      return;
    }
    
    addSprite(currentX, currentY, pixel);
    
    if (tile.some(t => t.type === target)) {
      clearInterval(graphInterval);
      winLevel();
    }
    
  }, 100); 
});

function failGraph() {
  playTune(sfxFail);
  addText("MISSED", { x: 5, y: 7, color: color`2` });
  
  setTimeout(() => {
    getAll(pixel).forEach(p => p.remove());
    clearText();
    updateScreen();
    calculating = false;
  }, 1000);
}

function winLevel() {
  playTune(sfxWin);
  addText("SOLVED", { x: 5, y: 7, color: color`3` });
  
  setTimeout(() => {
    startLevel(level + 1);
  }, 1500);
}