/*
@title: Snake
@author: Darxander6
@description: snake eats food ,gets bigger
@tags: ['animal','replayable'dsa]
@addedOn: 2026-05-08
*/

const snakeHead = "h";
const snakeBody = "b";
const food = "f";

setLegend(
  [ snakeHead, bitmap`
................
......2.........
.....DDDDDDD....
.....D402D2D....
.....DDDDD333...
.....D402D2D....
.....DDDDDDD....
................
................
................
................
................
................
................
................
................` ],
  [ snakeBody, bitmap`
................
................
.....444444.....
.....444444.....
.....444444.....
................
................
................
................
................
................
................
................
................
................
................` ],
  [ food, bitmap`
.........4D.....
........C.......
......3333......
.....333333.....
.....333333..6..
.....333333.....
.....333333.....
......3333......
................
................
................
................
................
................
................
................` ]
);

setMap(map`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
`);

let snake = [{x: 8, y: 8}];
let direction = "right";

function spawnFood() {
  if (getAll(food).length === 0) {
    addSprite(
      Math.floor(Math.random() * 16),
      Math.floor(Math.random() * 16),
      food
    );
  }
}

spawnFood();

function drawSnake() {
  // remove everything
  getAll(snakeHead).forEach(s => s.remove());
  getAll(snakeBody).forEach(s => s.remove());

  // draw snake
  snake.forEach((part, i) => {
    addSprite(part.x, part.y, i === 0 ? snakeHead : snakeBody);
  });
}
function moveSnake() {
  let head = { ...snake[0] };

  if (direction === "right") head.x++;
  if (direction === "left") head.x--;
  if (direction === "up") head.y--;
  if (direction === "down") head.y++;

  // wrap around screen
  head.x = (head.x + 16) % 16;
  head.y = (head.y + 16) % 16;

  snake.unshift(head);

  // check food collision
  let ate = false;
  let foods = getAll(food);
  foods.forEach(f => {
    if (f.x === head.x && f.y === head.y) {
      f.remove();
      spawnFood();
      ate = true;
    }
  });

  if (!ate) {
    snake.pop();
  }

  // self collision = reset
  for (let i = 1; i < snake.length; i++) {
    if (snake[i].x === head.x && snake[i].y === head.y) {
      snake = [{x: 8, y: 8}];
      direction = "right";
    }
  }

  drawSnake();
}

// controls
onInput("w", () => direction = "up");
onInput("s", () => direction = "down");
onInput("a", () => direction = "left");
onInput("d", () => direction = "right");

// game loop
setInterval(moveSnake, 200);
