const player = "p"
const food = "f"

setLegend(
  [ player, bitmap`
................
................
................
................
................
................
................
.......43.......
.......44.......
................
................
................
................
................
................
................` ],
  [ food, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................` ]
)

setSolids([ player, food ])

let level = 0
const levels = [
  map`
p.
..`
]

setMap(levels[level])

// Move the snake
onInput("d", () => {
  getFirst(player).x += 1
})
onInput("a", () => {
  getFirst(player).x -= 1
})
onInput("w", () => {
  getFirst(player).y -= 1
})
onInput("s", () => {
  getFirst(player).y += 1
})

// Check for food collision
afterInput(() => {
  const playerSprite = getFirst(player)
  const foodSprites = getAll(food)

  for (let i = 0; i < foodSprites.length; i++) {
    const foodSprite = foodSprites[i]
    if (playerSprite.x === foodSprite.x && playerSprite.y === foodSprite.y) {
      // Add a new food sprite
      addSprite(foodSprite.x, foodSprite.y, food)
    }
  }
})