/*
@title: Maze Combat Escape
@author: You
@tags: []
@addedOn: 2026-01-30
*/

const playerR = "p"
const playerL = "l"
const wall = "w"
const enemy = "m"
const bullet = "b"
const exit = "e"
const key = "k"
const door = "d"
const ammoPack = "a"

let facing = "right"
let ammo = 5
let hasKey = false
let isResetting = false
let isSwitching = false

setLegend(
[playerR, bitmap`
................
.......000......
.......0.0......
......0..0......
......0...0.....
....0003.30.....
....0.0...0.....
....0.05550.....
......0...0.....
.....0....0.....
.....0...0......
......000.......
......0.0.......
.....00.00......
................
................`],

[playerL, bitmap`
................
......000.......
......0.0.......
.....0..0.......
.....0...0......
.....03.300.....
.....0...0.0....
.....05550.0....
.....0...0......
....0....0......
.....0...0......
......000.......
.......0.0......
......00.00.....
................
................`],

[wall, bitmap`
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111
1111111111111111`],

[enemy, bitmap`
................
.....333333.....
....3......3....
....3.33.33.....
....3......3....
.....333333.....
................
................
................
................
................
................
................
................
................
................`],

[bullet, bitmap`
................
................
......666.......
......666.......
......666.......
................
................
................
................
................
................
................
................
................
................
................`],

[key, bitmap`
.......6........
......666.......
.....66.66......
......666.......
.......6........
................
................
................
................
................
................
................
................
................
................
................`],

[door, bitmap`
4444444444444444
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4..............4
4444444444444444`],

[exit, bitmap`
....222222......
....2....2......
....2....2......
....222222......
................
................
................
................
................
................
................
................
................
................
................
................`],

[ammoPack, bitmap`
.......5........
......555.......
.......5........
................
................
................
................
................
................
................
................
................
................
................
................
................`]
)

setSolids([playerR, playerL, wall, door])

let level = 0

const levels = [
map`
wwwwww
wp..kw
w.m..w
w..d.w
w...ew
wwwwww`,

map`
wwwwww
wp...w
w.mmkw
w..d.w
w..aew
wwwwww`,

map`
wwwwwww
wp....w
w.m.mkw
w...d.w
w.a..ew
wwwwwww`,

map`
wwwwwwww
wp.....w
w.mmm.kw
w..a.d.w
w...m.ew
wwwwwwww`,

map`
wwwwwwww
wp..m..w
w.mmm.kw
w..a.d.w
w...m.ew
wwwwwwww`
]

setMap(levels[level])

function getPlayer() {
  return getFirst(playerR) || getFirst(playerL)
}

function resetLevel() {
  ammo = 5
  hasKey = false
  clearText()
  setMap(levels[level])
  isResetting = false
}

function nextLevel() {
  clearText()
  level++
  if (level < levels.length) setMap(levels[level])
  else addText("YOU WIN!", { y: 6, color: color`2` })
  isSwitching = false
}

onInput("w", () => getPlayer().y -= 1)
onInput("s", () => getPlayer().y += 1)

onInput("a", () => {
  const p = getPlayer()
  facing = "left"
  addSprite(p.x - 1, p.y, playerL)
  p.remove()
})

onInput("d", () => {
  const p = getPlayer()
  facing = "right"
  addSprite(p.x + 1, p.y, playerR)
  p.remove()
})

onInput("j", () => {
  if (ammo <= 0 || isResetting || isSwitching) return
  const p = getPlayer()
  ammo--
  if (facing === "right") addSprite(p.x + 1, p.y, bullet)
  else addSprite(p.x - 1, p.y, bullet)
})

setInterval(() => {
  if (isResetting || isSwitching) return
  getAll(bullet).forEach(b => {
    if (facing === "right") b.x += 1
    else b.x -= 1
  })
}, 150)

setInterval(() => {
  if (isResetting || isSwitching) return
  getAll(enemy).forEach(e => {
    const dir = Math.floor(Math.random() * 4)
    if (dir === 0) e.x += 1
    if (dir === 1) e.x -= 1
    if (dir === 2) e.y += 1
    if (dir === 3) e.y -= 1
  })
}, 600)

afterInput(() => {
  if (isResetting || isSwitching) return

  tilesWith(bullet, enemy).forEach(tile => tile.forEach(s => s.remove()))

  if (
    tilesWith(playerR, enemy).length > 0 ||
    tilesWith(playerL, enemy).length > 0
  ) {
    addText("CAUGHT!", { y: 6, color: color`3` })
    isResetting = true
    setTimeout(resetLevel, 700)
  }

  if (
    tilesWith(playerR, ammoPack).length ||
    tilesWith(playerL, ammoPack).length
  ) {
    ammo += 3
    getFirst(ammoPack).remove()
  }

  if (
    tilesWith(playerR, key).length ||
    tilesWith(playerL, key).length
  ) {
    hasKey = true
    getFirst(key).remove()
  }

  if (
    hasKey &&
    (tilesWith(playerR, door).length ||
     tilesWith(playerL, door).length)
  ) {
    getFirst(door).remove()
    setSolids([playerR, playerL, wall])
  }

  if (
    tilesWith(playerR, exit).length ||
    tilesWith(playerL, exit).length
  ) {
    addText("SUCCESS!", { y: 6, color: color`4` })
    addText("Switching level...", { y: 8, color: color`4` })
    isSwitching = true
    setTimeout(nextLevel, 900)
  }
})
