/*
@title: Sprig Arcade
@author: Wowstar
@tags: ['arcade', 'game', 'games']
@addedOn: 2025-11-13
*/
 
// ------------------ Game States ------------------
let gameState = "menu"
let previousGame = null;

// ------------------ Legend ------------------
const player = "p";
const box = "b";
const rock = "g";
const wall = "w";

setLegend(
  [ player, bitmap`
................
................
.....00L101.....
....0000000L0...
...0000000000...
....0.....00....
....0.0.02.0....
....0......0....
....0......0....
....00....0.....
......00000.....
......0...0.....
....000...000...
................
................
................`],
  [ box, bitmap`
................
................
................
...000000000....
...0LLLLLLL0....
...0L11111L0....
...0L10001L0....
...0L10001L0....
...0L10001L0....
...0L11111L0....
...0LLLLLLL0....
...000000000....
................
................
................
................`],
  [ rock, bitmap`
................
................
................
....LLLLLLL.....
...LL11111LL....
..LL11LLL11LL...
..L11LL1LL11L...
..L11LL11LL1L...
..LL11L11L11L...
...LL1LLLL1LL...
....L11LL11L....
....LL1111LL....
.....LLLLLL.....
................
................
................`],
  [ wall, bitmap`
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000`]
);

// ------------------ Rock Game Levels ------------------
let rockLevel = 0;
const rockLevels = [
  map`
p....
.....
.b...
.....
..g..`,
  map`
p.w.
.bwg
....
..bg`,
  map`
pwg....w.........
.wwww......w.....
....w..w.b.w.b...
www.w......w..b..
....wwwww.wwwww.w
.wwww.....w......
.w....wwwwwwg....
.w..b......ww.www
.ww...g.ww.w.....
..wwwwwww..w.....
.b........gw....g`,
  map`
pw.....w.......g
...www.w.www....
wwww.w...w.w.b..
g..wwwwwww.w....
......www..wwww.
.b..w...www...w.
...wwww...wwwww.
.ww...www.......
....w...wwwwwwww
wwwwwww.w.......
...gw...w..g....
...ww.www.www.b.
.b..w.....w.w...
..w.wwwwwww.w...
..w....w....www.
..w.w.....w.....`,
  map`
pw.g..w..w...........
.w....w..w........g..
......wwww...........
wwww...........wwwwww
...w...........w.....
...w....b......w.....
...w...........w.....
...w...........wwwwww
wwww.................
............b........
..................b..
.g...................
.....................
.....................
.w.w.w.w.w.w.w.w.w.w.
..wgw.w.w.w.w.w.w.w.w
.........www.........
..www...w............
..wwww.....ww.wwww...
..wwww.....ww.w..w.b.
.wwwwwwwwwwwwww......`,
  map`
p......w.
......bwg
.........
.......bg
.wwwwwwww
.......w.
......bwg
.........
.......bg`,
  map`
pwg....w.........
.wwww......w.....
....w..w.b.w.b...
www.w......w..b..
....wwwww.wwwww.w
.wwww.....w......
.w....wwwwwwg....
.w..b......ww.www
.ww...g.ww.w.....
..wwwwwww..w.....
.b........gw....g
w........wwww..ww
gwwwww.wwwg..wwwg
.......www..bwww.
..b.b............
.................`,
];

setSolids([ player, box, wall ]);
setPushables({ [player]: [box] });

// ------------------ Menu Functions ------------------
function showMenu() {
  gameState = "menu";
  clearText();
  addText("Sprig Arcade", { y: 1, color: color`3` });
  addText(" ", {y: 2} );
  addText(" I: Rock Game", { y: 3, color: color`7` });
  addText("   K: Other Game", { y: 4, color: color`7` });
  addText("L: Controls", { y: 5, color: color`7` });
  
  setMap(map`
......
......
......
......
......
......`);
}

function showControls() {
  gameState = "showingControls";
  clearText();

  addText("Controls:", { y: 1, color: color`3` });
  addText("Move: W/A/S/D", { y: 2, color: color`7` });
  addText("Restart: J", { y: 3, color: color`7` });
  addText("Exit: L -> Yes", { y: 4, color: color`7` });
  addText("Back: W or K", { y: 5, color: color`5` });

  setMap(map`
......
......
......
......
......
......`);
}
function confirmExitMenu() {
  gameState = "confirmExit";
  clearText();
  addText("Go to Main Menu?", { y: 2, color: color`3` });
  addText("I: Yes", { y: 3, color: color`7` });
  addText("K: No", { y: 4, color: color`7` });

  setMap(map`
......
......
......
......
......
......`);
}

// ------------------ Input ------------------
onInput("i", () => {
  if (gameState === "menu") {
    gameState = "rockGame";
    rockLevel = 0;
    setMap(rockLevels[rockLevel]);
    clearText();
  } else if (gameState === "confirmExit") {
    showMenu();
  }
});

onInput("k", () => {
  if (gameState === "menu") {
    gameState = "otherGame";
    clearText();
    addText("Coming soon", { y: 4, color: color`5` });
    setMap(map`
......
......
......
......
......
......`);
  } else if (gameState === "showingControls") {
    showMenu(); // return to menu
  } else if (gameState === "confirmExit") {
    // no, return to previous game
    if (previousGame === "rockGame") setMap(rockLevels[rockLevel]);
    gameState = previousGame;
    clearText();
  }
});

onInput("l", () => {
  if (gameState === "rockGame" || gameState === "otherGame") {
    previousGame = gameState;
    confirmExitMenu();
  } else if (gameState === "menu") {
    showControls();
  }
});

onInput("w", () => {
  if (gameState === "showingControls") {
    showMenu();
  }
});

// ------------------ Rock Game Controls ------------------
onInput("w", () => { if (gameState === "rockGame") getFirst(player).y -= 1; });
onInput("a", () => { if (gameState === "rockGame") getFirst(player).x -= 1; });
onInput("s", () => { if (gameState === "rockGame") getFirst(player).y += 1; });
onInput("d", () => { if (gameState === "rockGame") getFirst(player).x += 1; });
onInput("j", () => { if (gameState === "rockGame") setMap(rockLevels[rockLevel]); });

// ------------------ Rock Game Logic ------------------
afterInput(() => {
  if (gameState !== "rockGame") return;

  const numberCovered = tilesWith(rock, box).length;
  const targetNumber = tilesWith(rock).length;

  if (numberCovered === targetNumber) {
    rockLevel += 1;
    const nextLevel = rockLevels[rockLevel];
    if (nextLevel !== undefined) {
      setMap(nextLevel);
    } else {
      addText("L to return to menu", { y: 4, color: color`3` });
      addText("You win!", { y: 3, color: color`4` });
      previousGame = "rockGame";
      gameState = "otherGame";
    }
  }
});

// ------------------ Start ------------------
showMenu();
