const seed = "s"
const sprout = "p"
const wall = "w"
const ground = "g"
const rock = "r"
const flower = "f"

// Sprites
setLegend(
  // Seed - green circle
  [ seed, bitmap`
................
................
.......DD.......
......DDDD......
.....DDDDDD.....
......DDDD......
.......DD.......
................
................
................
................
................
................
................
................
................` ],

  // Sprout - green
  [ sprout, bitmap`
................
................
.......44.......
......4444......
.....444444.....
......4444......
.......44.......
................
................
................
................
................
................
................
................
................` ],

  // Wall - black
  [ wall, bitmap`
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000` ],

  // Ground - blank
  [ ground, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................` ],

  // Rock - dark gray
  [ rock, bitmap`
................
......LL........
.....LLLL.......
.....LLLL.......
......LL........
......LL........
.......L........
................
................
................
................
................
................
................
................
................` ],

  // Flower - pink
  [ flower, bitmap`
................
.......88.......
......8888......
.....888888.....
......8888......
.......88.......
................
................
................
................
................
................
................
................
................
................` ]
)

// Solids
setSolids([seed, wall, rock])

// Map
const levels = [
  map`
wwwwwwwwwwwww
wggggrggggrgw
wgrggggsggggw
wgggggrgggggw
wgrgggggggrgw
wggggrggggrgw
wwwwwwwwwwwww`
]

let level = 0
setMap(levels[level])

// Move seed - crash-proof
function moveSeed(dx, dy) {
  const s = getFirst(seed)
  const nx = s.x + dx
  const ny = s.y + dy

  // Check boundaries
  if (nx < 0 || nx >= width() || ny < 0 || ny >= height()) return

  const targetTile = getTile(nx, ny)
  if (!targetTile || targetTile.some(t => t.type === wall || t.type === rock)) return

  const currentTile = getTile(s.x, s.y)
  if (currentTile && !currentTile.some(t => t.type === wall || t.type === rock)) {
    addSprite(s.x, s.y, sprout)
  }

  s.x = nx
  s.y = ny
}

// WASD controls
onInput("w", () => moveSeed(0, -1))
onInput("s", () => moveSeed(0, 1))
onInput("a", () => moveSeed(-1, 0))
onInput("d", () => moveSeed(1, 0))

// Restart
onInput("j", () => setMap(levels[level]))

// Flower spawn & win check
afterInput(() => {
  // Flower spawn
  if (Math.random() < 0.2) {
    const emptyTiles = []
    for (let x = 0; x < width(); x++) {
      for (let y = 0; y < height(); y++) {
        const tile = getTile(x, y)
        if (!tile) continue
        if (!tile.some(t => t.type === wall || t.type === rock || t.type === sprout || t.type === flower)) {
          emptyTiles.push({ x, y })
        }
      }
    }
    if (emptyTiles.length > 0) {
      const t = emptyTiles[Math.floor(Math.random() * emptyTiles.length)]
      addSprite(t.x, t.y, flower)
    }
  }

  // win screen
  let allFilled = true
  for (let x = 0; x < width(); x++) {
    for (let y = 0; y < height(); y++) {
      const tile = getTile(x, y)
      if (!tile) continue
      if (tile.some(t => t.type === ground) &&
          !tile.some(t => t.type === sprout || t.type === flower)) {
        allFilled = false
      }
    }
  }

  if (allFilled) {
    addText("All tiles covered!", { x: 2, y: 3, color: color`4` })
    disableInputs()
  }
})
