/*
@title: Vermin Watch
@description: Sprig-native Game & Watch Vermin remake.
@author: ssoggytacoman
@addedOn: 2026-06-05
@tags: ['retro']
*/

const d0 = "0";
const d1 = "1";
const d2 = "2";
const d3 = "3";
const d4 = "4";
const d5 = "5";
const d6 = "6";
const d7 = "7";
const d8 = "8";
const d9 = "9";

const line = "f";
const boxH = "c";
const boxCorner = "b";
const boxV = "g";

const man = "p";
const armL = "q";
const armR = "w";
const hitL = "e";
const hitR = "R";

const dirtLow = "u";
const dirtMid = "y";
const dirtHigh = "m";

const moleL = "n";
const moleC = "N";
const moleR = "o";
const moleHit = "j";
const moleMiss = "v";
const missIcon = "x";

const DIGITS = [d0, d1, d2, d3, d4, d5, d6, d7, d8, d9];

const DYNAMIC_TYPES = [
  d0, d1, d2, d3, d4, d5, d6, d7, d8, d9,
  man, armL, armR, hitL, hitR,
  dirtLow, dirtMid, dirtHigh,
  moleL, moleC, moleR, moleHit, moleMiss,
  missIcon
];

const ROW_MAN = 1;
const ROW_MOLE = 2;
const ROW_LINE = 3;
const ROW_DIRT = 5;

const MOLE_STAGE = 3;
const MISS_STAGE = 5;
const RETREAT_DONE = 4;
const HIT_VISIBLE_MS = 430;
const MIN_SPEED = 300;

const sfxMove = tune`
25: C5~25
`;

const sfxStep = tune`
22: C4~22
`;

const sfxHit = tune`
25: G5~25,
25: C6~25
`;

const sfxMiss = tune`
55: C4~55,
80: C3~80
`;

const sfxStart = tune`
25: C5~25,
25: G5~25
`;

const sfxOver = tune`
70: C4~70,
70: G3~70,
100: C3~100
`;

setLegend(
  [moleHit, bitmap`
................
................
................
................
.....000000.....
...0000000000...
..000000000000..
..000..00..000..
..000000000000..
...0000000000...
....00000000....
...00......00...
..00........00..
................
................
................`],

  [moleMiss, bitmap`
................
................
................
................
.....00000......
...000000000....
..0000000000....
.0000.00.0000...
.00000000000....
..000000000.....
...000000.......
...00...00......
................
................
................
................`],

  [moleL, bitmap`
................
................
................
................
......0000......
....00000000....
..0000000000....
.00000000000....
0000.00.0000....
00000000000.....
..00000000......
..00.....00.....
................
................
................
................`],

  [moleC, bitmap`
................
................
................
................
.....000000.....
...0000000000...
..000000000000..
..000..00..000..
..000000000000..
...0000000000...
....00000000....
...00......00...
................
................
................
................`],

  [moleR, bitmap`
................
................
................
................
....0000........
...00000000.....
...0000000000...
...00000000000..
...0000.00.0000.
....00000000000.
.....00000000...
.....00.....00..
................
................
................
................`],

  [dirtLow, bitmap`
................
................
................
................
................
................
................
................
................
................
................
.....0000.......
...00000000.....
..000....000....
................
................`],

  [dirtMid, bitmap`
................
................
................
................
................
................
................
.......000......
.....000000.....
...000....00....
................
.....0000.......
...00000000.....
..000....000....
................
................`],

  [dirtHigh, bitmap`
................
................
................
....000.........
..000000........
.000...00.......
................
.......000......
.....000000.....
...000....00....
................
.....0000.......
...00000000.....
..000....000....
................
................`],

  [hitL, bitmap`
................
................
................
................
................
................
................
................
.......00.......
......00........
.....00.........
....0000000.....
...000000000....
....0000000.....
................
................`],

  [hitR, bitmap`
................
................
................
................
................
................
................
................
......00........
.......00.......
........00......
.....0000000....
....000000000...
.....0000000....
................
................`],

  [armL, bitmap`
.00000000.......
0000000000......
.00000000.......
...00...........
....00..........
.....00.........
......00........
.......00.......
........0.......
................
................
................
................
................
................
................`],

  [armR, bitmap`
.......00000000.
......0000000000
.......00000000.
.........00.....
........00......
.......00.......
......00........
.....00.........
....0...........
................
................
................
................
................
................
................`],

  [man, bitmap`
................
................
......0000......
....00000000....
...0000000000...
...000..0000....
...0000000000...
....00000000....
......0000......
..0...0000...0..
...0..0000..0...
....0.0000.0....
.....000000.....
.....0.00.0.....
....0..00..0....
...0........0...`],

  [missIcon, bitmap`
................
................
................
................
.....0000.......
....000000......
...00000000.....
...00.00.00.....
...00000000.....
....000000......
.....0000.......
....00..00......
................
................
................
................`],

  [d0, bitmap`
................
................
................
.....000000.....
....00....00....
....00....00....
....00....00....
....00....00....
....00....00....
.....000000.....
................
................
................
................
................
................`],

  [d1, bitmap`
................
................
................
.......00.......
......000.......
.......00.......
.......00.......
.......00.......
.......00.......
.....000000.....
................
................
................
................
................
................`],

  [d2, bitmap`
................
................
................
.....000000.....
....00....00....
..........00....
.......0000.....
.....000........
....00..........
....00000000....
................
................
................
................
................
................`],

  [d3, bitmap`
................
................
................
.....000000.....
....00....00....
..........00....
......00000.....
..........00....
....00....00....
.....000000.....
................
................
................
................
................
................`],

  [d4, bitmap`
................
................
................
....00....00....
....00....00....
....00....00....
....00000000....
..........00....
..........00....
..........00....
................
................
................
................
................
................`],

  [d5, bitmap`
................
................
................
....00000000....
....00..........
....00..........
....000000......
..........00....
....00....00....
.....000000.....
................
................
................
................
................
................`],

  [d6, bitmap`
................
................
................
.....000000.....
....00..........
....00..........
....000000......
....00....00....
....00....00....
.....000000.....
................
................
................
................
................
................`],

  [d7, bitmap`
................
................
................
....00000000....
..........00....
.........00.....
........00......
.......00.......
......00........
......00........
................
................
................
................
................
................`],

  [d8, bitmap`
................
................
................
.....000000.....
....00....00....
....00....00....
.....000000.....
....00....00....
....00....00....
.....000000.....
................
................
................
................
................
................`],

  [d9, bitmap`
................
................
................
.....000000.....
....00....00....
....00....00....
.....000000.....
..........00....
..........00....
.....000000.....
................
................
................
................
................
................`],

  [line, bitmap`
................
................
................
................
................
................
................
..0000000000....
..0000000000....
................
................
................
................
................
................
................`],

  [boxH, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
0000000000000000
0000000000000000
................
................`],

  [boxCorner, bitmap`
................
................
................
................
................
................
................
................
................
................
................
................
0000000000000000
0000000000000000
..............00
..............00`],

  [boxV, bitmap`
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00
..............00`]
);

setSolids([]);

const baseMap = map`
..........
..........
..........
f.f.f.f.ff
..........
..........
cccb......
...g......`;

// Line dashes are mostly on x 0, 2, 4, 6, 8, plus a right edge segment.
// Mole graphics are drawn ABOVE the line row, so they no longer cut through it.
const holeX = [1, 3, 5, 7, 9];

// Game A: no center hole.
// Game B: all five holes.
const gameAHoles = [0, 1, 3, 4];
const gameBHoles = [0, 1, 2, 3, 4];

// Three Vermin positions.
// Position 0 covers holes 0 and 2.
// Position 1 covers holes 1 and 3.
// Position 2 covers holes 2 and 4.
const slots = [
  { body: 3, left: 0, right: 2 },
  { body: 5, left: 1, right: 3 },
  { body: 7, left: 2, right: 4 }
];

let state = "ready";
let game = 0;
let pos = 1;

let score = 0;
let misses = 0;
let shownMisses = 0;

let enemies = [];

let gameSpeed = 1000;
let scorePrev = 9;
let molesAtOnce = 0;
let molesAtOnceGame = 0;
let savedSpeedBeforeMiss = 1000;

let timer = null;
let hitTimeout = null;

let hitActive = false;
let hitHole = -1;
let hitSide = "";
let hitPos = 1;

function playSound(sound) {
  playTune(sound);
}

function clearTimer() {
  if (timer !== null) {
    clearInterval(timer);
    timer = null;
  }
}

function clearHitTimer() {
  if (hitTimeout !== null) {
    clearTimeout(hitTimeout);
    hitTimeout = null;
  }
}

function startTimer() {
  clearTimer();
  timer = setInterval(gameStep, gameSpeed);
}

function setGameSpeed(nextSpeed) {
  if (nextSpeed < MIN_SPEED) {
    nextSpeed = MIN_SPEED;
  }

  if (nextSpeed !== gameSpeed) {
    gameSpeed = nextSpeed;
    startTimer();
  }
}

function removeSprites(type) {
  const sprites = getAll(type);

  for (let i = 0; i < sprites.length; i++) {
    sprites[i].remove();
  }
}

function clearDynamic() {
  for (let i = 0; i < DYNAMIC_TYPES.length; i++) {
    removeSprites(DYNAMIC_TYPES[i]);
  }
}

function activeHoles() {
  return game === 1 ? gameAHoles : gameBHoles;
}

function resetGameState() {
  pos = 1;
  score = 0;
  misses = 0;
  shownMisses = 0;

  enemies = [];

  molesAtOnce = 0;
  molesAtOnceGame = 0;
  scorePrev = game === 2 ? 6 : 9;
  savedSpeedBeforeMiss = gameSpeed;

  hitActive = false;
  hitHole = -1;
  hitSide = "";
  hitPos = 1;
}

function drawAll() {
  clearDynamic();
  drawHud();
  drawEnemies();
  drawPlayer();
}

function drawHud() {
  if (state === "ready") {
    drawScore(0);
    return;
  }

  for (let i = 0; i < shownMisses; i++) {
    addSprite(i, 7, missIcon);
  }

  drawScore(score);
}

function drawScore(value) {
  const text = String(value % 1000);
  const startX = 10 - text.length;

  for (let i = 0; i < text.length; i++) {
    addSprite(startX + i, 7, DIGITS[Number(text[i])]);
  }
}

function drawPlayer() {
  const p = slots[hitActive ? hitPos : pos];

  addSprite(p.body, ROW_MAN, man);

  if (hitActive && hitSide === "L") {
    addSprite(holeX[p.left], ROW_MOLE, hitL);
    addSprite(holeX[p.right], ROW_MAN, armR);
  } else if (hitActive && hitSide === "R") {
    addSprite(holeX[p.left], ROW_MAN, armL);
    addSprite(holeX[p.right], ROW_MOLE, hitR);
  } else {
    addSprite(holeX[p.left], ROW_MAN, armL);
    addSprite(holeX[p.right], ROW_MAN, armR);
  }
}

function moleSpriteForHole(hole) {
  if (hole < 2) {
    return moleL;
  }

  if (hole === 2) {
    return moleC;
  }

  return moleR;
}

function dirtSpriteForStage(stage) {
  if (stage <= 0) {
    return dirtLow;
  }

  if (stage === 1) {
    return dirtMid;
  }

  return dirtHigh;
}

function drawDirt(x, stage) {
  // Dirt is kept low, above the miss box/score, not on the line.
  addSprite(x, ROW_DIRT, dirtSpriteForStage(stage));
}

function drawEnemy(enemy) {
  const x = holeX[enemy.hole];

  if (enemy.missed) {
    if (enemy.retreat === 0) {
      drawDirt(x, 2);
      addSprite(x, ROW_MOLE, moleMiss);
    } else if (enemy.retreat === 1) {
      drawDirt(x, 2);
    } else if (enemy.retreat === 2) {
      drawDirt(x, 1);
    } else {
      drawDirt(x, 0);
    }

    return;
  }

  if (enemy.stage < MOLE_STAGE) {
    drawDirt(x, enemy.stage);
  } else {
    drawDirt(x, 2);
    addSprite(x, ROW_MOLE, moleSpriteForHole(enemy.hole));
  }
}

function drawEnemies() {
  for (let i = 0; i < enemies.length; i++) {
    drawEnemy(enemies[i]);
  }

  if (hitActive && hitHole >= 0) {
    drawDirt(holeX[hitHole], 2);
    addSprite(holeX[hitHole], ROW_MOLE, moleHit);
  }
}

function isCovered(hole) {
  const p = slots[pos];
  return hole === p.left || hole === p.right;
}

function hittableSideForHole(hole) {
  const p = slots[pos];

  if (hole === p.left) {
    return "L";
  }

  if (hole === p.right) {
    return "R";
  }

  return "";
}

function showReady() {
  state = "ready";
  game = 0;

  clearTimer();
  clearHitTimer();

  gameSpeed = 1000;
  resetGameState();

  setMap(baseMap);
  drawAll();
}

function startGame(selectedGame) {
  state = "play";
  game = selectedGame;

  clearHitTimer();

  if (selectedGame === 1) {
    gameSpeed = 1000;
    scorePrev = 9;
  } else {
    gameSpeed = 650;
    scorePrev = 6;
  }

  resetGameState();

  if (selectedGame === 1) {
    scorePrev = 9;
  } else {
    scorePrev = 6;
  }

  savedSpeedBeforeMiss = gameSpeed;

  playSound(sfxStart);

  setMap(baseMap);
  drawAll();
  startTimer();
}

function activeEnemyCount() {
  let count = 0;

  for (let i = 0; i < enemies.length; i++) {
    if (!enemies[i].missed) {
      count += 1;
    }
  }

  return count;
}

function hasSurfacedEnemy() {
  for (let i = 0; i < enemies.length; i++) {
    if (!enemies[i].missed && enemies[i].stage >= MOLE_STAGE) {
      return true;
    }
  }

  return false;
}

function updateMolesAtOnce() {
  while (score >= scorePrev) {
    if (molesAtOnce < 2) {
      molesAtOnce += 1;
    } else {
      molesAtOnce = 0;
    }

    if (game === 2) {
      scorePrev += 7 - (molesAtOnce < 2 ? 1 : 2);
    } else {
      scorePrev += 7 - molesAtOnce;
    }
  }

  molesAtOnceGame = molesAtOnce;

  if (game === 2 && score > 2 && molesAtOnceGame < 2) {
    molesAtOnceGame += 1;
  }
}

function shouldDelayNewMole() {
  if (molesAtOnceGame !== 1) {
    return false;
  }

  if (activeEnemyCount() === 0) {
    return false;
  }

  for (let i = 0; i < enemies.length; i++) {
    const enemy = enemies[i];

    if (!enemy.missed && enemy.stage >= 2) {
      return false;
    }
  }

  return !hasSurfacedEnemy();
}

function spawnEnemyIfNeeded() {
  updateMolesAtOnce();

  const current = activeEnemyCount();

  if (current > molesAtOnceGame) {
    return;
  }

  if (shouldDelayNewMole()) {
    return;
  }

  const options = [];
  const holes = activeHoles();

  for (let i = 0; i < holes.length; i++) {
    const hole = holes[i];
    let occupied = false;

    for (let j = 0; j < enemies.length; j++) {
      if (enemies[j].hole === hole) {
        occupied = true;
      }
    }

    if (!occupied && hole !== hitHole) {
      options.push(hole);
    }
  }

  if (options.length === 0) {
    return;
  }

  const hole = options[Math.floor(Math.random() * options.length)];

  enemies.push({
    hole,
    stage: 0,
    missed: false,
    retreat: 0
  });
}

function speedUp(amount) {
  if (gameSpeed > MIN_SPEED) {
    setGameSpeed(gameSpeed - amount);
  }
}

function addScore(points) {
  for (let i = 0; i < points; i++) {
    score += 1;
  }

  if (game === 1 && score === 10) {
    speedUp(350);
  } else if (score > 0 && score % 50 === 0) {
    if (gameSpeed > 500) {
      speedUp(100);
    } else if (gameSpeed > 440) {
      speedUp(40);
    } else if (gameSpeed > 400) {
      speedUp(20);
    } else if (gameSpeed > 360) {
      speedUp(10);
    } else {
      speedUp(5);
    }
  }
}

function startHit(hole) {
  const side = hittableSideForHole(hole);

  if (side === "") {
    return;
  }

  hitActive = true;
  hitHole = hole;
  hitSide = side;
  hitPos = pos;

  playSound(sfxHit);

  clearHitTimer();
  hitTimeout = setTimeout(() => {
    hitActive = false;
    hitHole = -1;
    hitTimeout = null;

    if (state === "play") {
      drawAll();
    }
  }, HIT_VISIBLE_MS);
}

function hitCoveredMoles() {
  const kept = [];

  for (let i = 0; i < enemies.length; i++) {
    const enemy = enemies[i];

    if (
      !enemy.missed &&
      enemy.stage >= MOLE_STAGE &&
      enemy.stage < MISS_STAGE &&
      isCovered(enemy.hole)
    ) {
      addScore(1);
      startHit(enemy.hole);
    } else {
      kept.push(enemy);
    }
  }

  enemies = kept;
}

function startMiss(enemy) {
  savedSpeedBeforeMiss = gameSpeed;

  misses += 1;
  enemy.missed = true;
  enemy.retreat = 0;

  playSound(sfxMiss);

  // Pause while the missed mole crawls back.
  setGameSpeed(1000);
}

function hasRetreatingEnemy() {
  for (let i = 0; i < enemies.length; i++) {
    if (enemies[i].missed) {
      return true;
    }
  }

  return false;
}

function advanceRetreatingEnemies() {
  playSound(sfxStep);

  for (let i = 0; i < enemies.length; i++) {
    if (enemies[i].missed) {
      enemies[i].retreat += 1;
    }
  }

  const before = enemies.length;
  const kept = [];

  for (let i = 0; i < enemies.length; i++) {
    const enemy = enemies[i];

    if (!enemy.missed || enemy.retreat < RETREAT_DONE) {
      kept.push(enemy);
    }
  }

  enemies = kept;

  if (before > enemies.length) {
    shownMisses = misses;

    if (misses >= 3) {
      endGame();
      return;
    }

    setGameSpeed(savedSpeedBeforeMiss);
  }
}

function advanceEnemies() {
  const kept = [];

  for (let i = 0; i < enemies.length; i++) {
    const enemy = enemies[i];

    if (enemy.missed) {
      kept.push(enemy);
      continue;
    }

    enemy.stage += 1;

    if (
      enemy.stage >= MOLE_STAGE &&
      enemy.stage < MISS_STAGE &&
      isCovered(enemy.hole)
    ) {
      addScore(1);
      startHit(enemy.hole);
      continue;
    }

    if (enemy.stage >= MISS_STAGE) {
      startMiss(enemy);
      kept.push(enemy);

      for (let j = i + 1; j < enemies.length; j++) {
        kept.push(enemies[j]);
      }

      enemies = kept;
      return;
    }

    kept.push(enemy);
  }

  enemies = kept;
}

function gameStep() {
  if (state !== "play") {
    return;
  }

  if (hasRetreatingEnemy()) {
    advanceRetreatingEnemies();
    drawAll();
    return;
  }

  playSound(sfxStep);
  advanceEnemies();

  if (state !== "play") {
    drawAll();
    return;
  }

  spawnEnemyIfNeeded();
  drawAll();
}

function moveLeft() {
  if (state !== "play") {
    return;
  }

  if (hitActive) {
    return;
  }

  if (pos <= 0) {
    return;
  }

  pos -= 1;

  playSound(sfxMove);
  hitCoveredMoles();
  drawAll();
}

function moveRight() {
  if (state !== "play") {
    return;
  }

  if (hitActive) {
    return;
  }

  if (pos >= 2) {
    return;
  }

  pos += 1;

  playSound(sfxMove);
  hitCoveredMoles();
  drawAll();
}

function endGame() {
  state = "over";
  game = 3;

  clearTimer();
  clearHitTimer();

  enemies = [];
  hitActive = false;
  hitHole = -1;
  hitSide = "";

  playSound(sfxOver);
  drawAll();
}

onInput("a", () => {
  moveLeft();
});

onInput("d", () => {
  moveRight();
});

onInput("j", () => {
  if (state === "ready" || state === "over") {
    startGame(1);
  }
});

onInput("k", () => {
  if (state === "ready" || state === "over") {
    startGame(2);
  }
});

onInput("l", () => {
  if (state === "ready" || state === "over") {
    startGame(2);
  }
});

showReady();
// trigger triage links
