const car = "c"
const wall = "w"
const oil = "o"
const coin = "i"
const flag = "f"
const boost = "b"

setLegend(
  [car, bitmap`
................
................
....333333......
...3.0000.3.....
..3.000000.3....
..3333333333....
...33333333.....
..3........3....
...3.3..3.3.....
................
................
................
................
................
................
................
  `],
  [wall, bitmap`
3333333333333333
3...............
3...............
3...............
3...............
3...............
3...............
3333333333333333
3333333333333333
................
................
................
................
................
................
................
  `],
  [oil, bitmap`
................
.....5555.......
...55555555.....
...55555555.....
....555555......
.....5555.......
................
................
................
................
................
................
................
................
................
................
  `],
  [coin, bitmap`
................
........6.......
.......666......
......66666.....
......66666.....
.......666......
........6.......
................
................
................
................
................
................
................
................
................
  `],
  [flag, bitmap`
................
....333333......
...32222223.....
...32222223.....
....333333......
......3.........
......3.........
......3.........
................
................
................
................
................
................
................
................
  `],
  [boost, bitmap`
................
....4444........
...488884.......
..48888884......
...488884.......
....4444........
................
................
................
................
................
................
................
................
................
................
  `]
)

setSolids([car, wall])

let score = 0
let sliding = false
let currentLevel = 0

const levels = [
  map`
wwwwwwwwwwww
w....i.....w
.w..o..o..w.
..w..f..w...
...w....w...
....c..w....
.....w......
wwwwwwwwwwww`,
  map`
wwwwwwwwwwww
w..i....i..w
.w..b..b..w.
..w..o..w...
...w.f..w...
....c..w....
.....w......
wwwwwwwwwwww`,
  map`
wwwwwwwwwwww
w..i..o..i.w
.w..b..b..w.
..w..f..w...
...w....w...
....c..w....
.....w......
wwwwwwwwwwww`
]

function loadLevel(n) {
  clearText()
  setMap(levels[n])
}

function slide(dx, dy) {
  const c = getFirst(car)
  if (!c) return
  let newX = c.x + dx
  let newY = c.y + dy
  const tile = getTile(newX, newY)
  if (tile.some(t => t.type === wall)) return
  getFirst(car).x = newX
  getFirst(car).y = newY
}

function endGame() {
  clearText()
  addText(`YOU WIN!\nCoins: ${score}`, {
    x: 2,
    y: 6,
    color: color`2`
  })
}

function nextLevel() {
  currentLevel++
  if (currentLevel < levels.length) {
    loadLevel(currentLevel)
  } else {
    endGame()
  }
}

onInput("w", () => {
  if (!sliding) {
    slide(0, -1)
    sliding = true
    setTimeout(() => {
      slide(0, -1)
      sliding = false
    }, 100)
  }
})
onInput("s", () => {
  if (!sliding) {
    slide(0, 1)
    sliding = true
    setTimeout(() => {
      slide(0, 1)
      sliding = false
    }, 100)
  }
})
onInput("a", () => {
  if (!sliding) {
    slide(-1, 0)
    sliding = true
    setTimeout(() => {
      slide(-1, 0)
      sliding = false
    }, 100)
  }
})
onInput("d", () => {
  if (!sliding) {
    slide(1, 0)
    sliding = true
    setTimeout(() => {
      slide(1, 0)
      sliding = false
    }, 100)
  }
})

afterInput(() => {
  const c = getFirst(car)
  const t = getTile(c.x, c.y)

  for (let obj of t) {
    if (obj.type === coin) {
      score++
      clearTile(c.x, c.y)
      addSprite(c.x, c.y, car)
    }

    if (obj.type === oil) {
      const dirs = [[1,0],[-1,0],[0,1],[0,-1]]
      const r = dirs[Math.floor(Math.random() * dirs.length)]
      slide(r[0], r[1])
    }

    if (obj.type === boost) {
      slide(2 * (c.x - (c.x - 1)), 2 * (c.y - (c.y - 1)))
    }

    if (obj.type === flag) {
      nextLevel()
    }
  }
})

loadLevel(currentLevel)
