/*
First time? Check out the tutorial game:
https://sprig.hackclub.com/gallery/getting_started

@title: Fighter
@author: 
@tags: []
@addedOn: 2024-00-00
*/

const player = "p"
const zombie1 = "a"
const zombie2 = "b"

setLegend(
  [ player, bitmap`
................
................
................
................
......000.......
......666.......
......666.......
....6333336.....
...66.333.66....
...6..333..6....
......333.......
......555.......
......555.......
......5.5.......
.....55.55......
................` ],
  [ zombie1, bitmap`
................
................
................
................
......000.......
......444.......
......444.......
....4333334.....
...44.333.44....
...4..333..4....
......333.......
......555.......
......555.......
......5.5.......
.....55.55......
................` ],
  [ zombie2, bitmap`
................
................
.....6.6.6......
.....66666......
.....44444......
.....44444......
......444.......
....4333334.....
...44.333.44....
...4..333..4....
......333.......
......555.......
......555.......
......5.5.......
.....55.55......
................` ],
  
)

setSolids([])

let level = 0
const levels = [
  map`
.........
....a....
.........
.........
....p....
.........
.........
.........
.........`,
  map`
...a....
........
........
...p....
........
........
........
........`,
  map`
a.....b..
.........
.........
.........
.........
........p
.........`,
  map`
.......
.b...p.
.......
.a.....
.......`
  
]

setMap(levels[level])

setPushables({
  [ player ]: []
})

onInput("s", () => {
  getFirst(player).y += 1
})
onInput("w", () => {
  getFirst(player).y -= 1
})
onInput("a", () => {
  getFirst(player).x -= 1
})
onInput("d", () => {
  getFirst(player).x += 1
})


afterInput(() => {

})

score = 0
currentLevel = 0
addText("Level: 1", { x: 1, y: 1, color: color`3` });
function gameOver() {
  // Display "Game Over" message
  addText("Game Over", { x: 5, y: 5, color: color`3` });
  setTimeout(() => {addText("Score: " + score + " ", { x: 5, y: 5, color: color`3` });},2000);
  clearTile(getFirst(player).x,getFirst(player).y);
  setTimeout(() => {
    addText("                                             ", { x: 5, y: 5, color: color`3` });
    score = 0;
    setMap(levels[0])
    currentLevel = 0
    addText("Level: 1", { x: 1, y: 1, color: color`3` });
  },4000);
}


setInterval(() => {
  if (getFirst(zombie2).x > getFirst(player).x){
    getFirst(zombie2).x -= 1
  }else if(getFirst(zombie2).x < getFirst(player).x){
    getFirst(zombie2).x += 1
  }else if(getFirst(zombie2).y < getFirst(player).y){
    getFirst(zombie2).y += 1
  }else if(getFirst(zombie2).y > getFirst(player).y){
    getFirst(zombie2).y -= 1
  }
},5000);

setInterval(() => {
  if (getFirst(zombie1).x > getFirst(player).x){
    getFirst(zombie1).x -= 1
  }else if(getFirst(zombie1).x < getFirst(player).x){
    getFirst(zombie1).x += 1
  }else if(getFirst(zombie1).y < getFirst(player).y){
    getFirst(zombie1).y += 1
  }else if(getFirst(zombie1).y > getFirst(player).y){
    getFirst(zombie1).y -= 1
  }
  if (getFirst(zombie2).x > getFirst(player).x){
    getFirst(zombie2).x -= 1
  }else if(getFirst(zombie2).x < getFirst(player).x){
    getFirst(zombie2).x += 1
  }else if(getFirst(zombie2).y < getFirst(player).y){
    getFirst(zombie2).y += 1
  }else if(getFirst(zombie2).y > getFirst(player).y){
    getFirst(zombie2).y -= 1
  }
},1000);

setInterval(() => {
  if(getFirst(zombie1).y == getFirst(player).y && getFirst(zombie1).x == getFirst(player).x){
    gameOver();
  }else if(currentLevel > 1 && getFirst(zombie2).y == getFirst(player).y && getFirst(zombie2).x == getFirst(player).x){
    gameOver();
  }else{
    score += 1
  }
  if (score > 3000 * ((currentLevel*currentLevel) +1) && currentLevel < levels.length){
    setMap(levels[currentLevel + 1])
    currentLevel += 1
    addText("Level: " + (currentLevel +1 ), { x: 1, y: 1, color: color`3` });
  }
},2);