version: "3.8"

services:
  yjs-client:
    env_file:
      - .env
    build:
      context: ./yjs-client
      dockerfile: Dockerfile
    ports:
      - "3000"

  yjs-signaling-server:
    env_file:
      - .env
    build:
      context: ./yjs-signaling-server
      dockerfile: Dockerfile
    ports:
      - "8080"
