setLegend(
  ["p", bitmap`
................
................
....000000......
....000000......
....000000......
....000000......
................
................
................
................
................
................
................
................
................
................`],
  ["e", bitmap`
................
................
................
....333333......
....333333......
....333333......
................
................
................
................
................
................
................
................
................
................`]
)

setMap(map`
........
........
........
........
........
........
........
...p....
`)

setSolids(["p"])

let player = getFirst("p")
let gameOver = false
let score = 0
let speed = 500

onInput("a", () => {
  if (!gameOver && player.x > 0) {
    player.x -= 1
  }
})

onInput("d", () => {
  if (!gameOver && player.x < 7) {
    player.x += 1
  }
})

onInput("w", () => {
  if (gameOver) {
    clearText()
    setMap(map`
........
........
........
........
........
........
........
...p....
`)
    player = getFirst("p")
    gameOver = false
    score = 0
    speed = 500
    gameLoop()
  }
})

function spawnEnemy() {
  let x = Math.floor(Math.random() * 8)
  addSprite(x, 0, "e")
}

function moveEnemies() {
  let enemies = getAll("e")
  for (let e of enemies) {
    e.y += 1

    if (!gameOver && e.x === player.x && e.y === player.y) {
      gameOver = true

      clearText()

      for (let en of getAll("e")) {
        en.remove()
      }
      
      addText("GAME OVER", { x: 3, y: 3, color: color`3` })
      addText("SCORE: " + score, { x: 4, y: 5, color: color`2` })
      addText("W TO RESTART", { x: 1, y: 7, color: color`1` })
      return
    }

    if (e.y >= 7) {
      e.remove()
    }
  }
}

function gameLoop() {
  if (gameOver) return

  spawnEnemy()
  moveEnemies()

  score += 1
  if (speed > 150) speed -= 5

  setTimeout(gameLoop, speed)
}

gameLoop()
