import "./games/sokoban.js";
import "./games/snake.js";
import "./games/two-player.js";
import "./games/replace-land.js";
import "./games/wall-bounce.js";
import "./games/sokoban-replace.js";
import "./games/lightsoff.js";
import "./games/snake-replace.js";
import "./games/gemini.js"
import "./games/blockfaker.js"
import "./games/suckyban.js"
import "./games/plantsvsmankind.js"
import "./games/axechess.js"
import "./games/brokenzengarden.js"
import "./games/twoButNotThree.js"
import "./games/maze.js"
import "./games/zen-garden.js"
