/*
@title: getting_started
@description: "Getting Started" is a tutorial game that guides players through basic game mechanics.
@author: leo, edits
@tags: ['tutorial']
@addedOn: 2022-07-26

Check the tutorial in the bottom right, the run button is in the top right.
Make sure to remix this tutorial if you want to save your progress!
*/

// define the sprites in our game// define the sprites in our game
const player = "p";
const box = "b";
const goal = "g";
const wall = "w";
const portal = "l"
const backdrop = "h";

// assign bitmap art to each sprite
setLegend(
  [ player, bitmap`
................
................
................
.......0........
.....006000.....
....06666600....
....06060660....
....08666860....
....06666660....
....0066660.....
......00000.....
......0...0.....
....800...008...
................
................
................`],
  [ box, bitmap`
................
................
................
................
................
.......D........
......333.......
......333.......
......333.......
................
................
................
................
................
................
................`],
  [ goal, bitmap`
................
................
................
................
................
................
...0000000000...
...0C......C0...
...0C......C0...
...0000000000...
...0CCCCCCCC0...
...0CCCCCCCC0...
...0000000000...
................
................
................`],
  [ wall, bitmap`
................
................
................
................
................
.....44444......
....444DDDDD....
...444DDDDDDD...
...44DDDDDDDD...
....4DDDDDDDD...
....DDDDDDDD....
................
................
................
................
................`],
  [ portal, bitmap`
................
................
................
................
................
.......HHH......
......H888H.....
......H828H.....
......H888H.....
.......HHH......
................
................
................
................
................
................`],
  [ backdrop,  bitmap`
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777
7777777777777777`],
);

// create game levels
let level = 0; // this tracks the level we are on
const levels = [
  map`
..p.
.b.g
....`,
  map`
p..
.b.
..g`,
  map`
p.wg
.b..
....
..w.`,
  map`
wpw.
wbw.
..ww
...g`,
  map`
p...l
wwwww
.....
..b..
....g`,
  map`
lpw.
www.
....
..bg`
];

setBackground(backdrop)

// set the map displayed to the current level
const currentLevel = levels[level];
setMap(currentLevel);

setSolids([ player, box, wall ]); // other sprites cannot go inside of these sprites

// allow certain sprites to push certain other sprites
setPushables({
  [player]: [box]
});

// inputs for player movement control
onInput("s", () => {
  getFirst(player).y += 1; // positive y is downwards
});

onInput("d", () => {
  getFirst(player).x += 1;
});

onInput("w", () => {
  getFirst(player).y -= 1; // positive y is downwards
});

onInput("a", () => {
  getFirst(player).x -= 1;
});

onInput("k", () => {
  getFirst(player).x += 3;
  getFirst(player).y += 2;
});

// input to reset level
onInput("i", () => {
  const currentLevel = levels[level]; // get the original map of the level

  // make sure the level exists before we load it
  if (currentLevel !== undefined) {
    clearText("");
    setMap(currentLevel);
  }
});

// these get run after every input
afterInput(() => {
  // count the number of tiles with goals
  const targetNumber = tilesWith(goal).length;
  
  // count the number of tiles with goals and boxes
  const numberCovered = tilesWith(goal, box).length;

  // if the number of goals is the same as the number of goals covered
  // all goals are covered and we can go to the next level
  if (numberCovered === targetNumber) {
    // increase the current level number
    level = level + 1;

    const currentLevel = levels[level];

    // make sure the level exists and if so set the map
    // otherwise, we have finished the last level, there is no level
    // after the last level
    if (currentLevel !== undefined) {
      setMap(currentLevel);
    } else {
      addText("you win!", { y: 4, color: color`2` });
    }
  }
});
