#ifndef TONE_MAP
#define TONE_MAP

// this file has been generated by gen_hash.c

// collision( 1):  d#2 <->   b1
// collision( 2):  d#2 <->   b1
// collision( 3):   f3 <->  d#1
// collision( 4):   c5 <->  f#1
// collision( 5):  d#2 <->   b1
// collision( 6):  d#8 <->   d5
// collision( 7):  g#3 <->   a2
// collision( 8):   c5 <->  f#1
// collision( 9):   f3 <->  d#1
// collision(10):  d#2 <->   b1
// collision(11):  d#2 <->   b1

// optimal size multiplier is 12! (2136 bytes)

#include <stdint.h>

static uint64_t fnv1_hash(void *key, int n_bytes) {
  unsigned char *p = (unsigned char *)key;
  uint64_t h = 14695981039346656037ul;
  for (int i = 0; i < n_bytes; i++)
    h = (h * 1099511628211) ^ p[i];
  return h;
}

extern uint16_t tone_map[1068];

#endif //TONE_MAP