import json

def add_to_metadata(filename, description):

    with open("games/" + filename, "r") as f:
        lines = f.readlines()

    added_description = False

    for i in range(len(lines)):
        if "@title" in lines[i]:
            lines.insert(i+1, "@description: " + description)
            added_description = True
            break

    if not added_description:
        print("The description was not able to be added. Please add this description manually.")
        print("Filename: " + filename)
        print("Description: " + description)
    
    else:
        # test if this overwrites or appends
        with open("games/" + filename, "w") as f:
            f.writelines(lines)

with open("scripts/descriptions.json", "r") as f:
    descriptions = json.load(f)

with open("scripts/all_games.json", "r") as f:
    all_games = json.load(f)

index = int(input("What description would you like to start at? "))

while True:

    filename = all_games[index]["filename"]

    pr_comment = None

    if "pr_comment" in all_games[index]:
        pr_comment = all_games[index]["pr_comment"]

    print(f"""  
        The filename is: {filename}

        The comment on the file was:
        {all_games[index]["file_comment"]}

        The comment on the pr was:
        {pr_comment}


        The description generated by ChatGPT is:
        {descriptions[filename]}

        """
    )

    is_ok = input("Is this description accurate? (y/n) ").lower() == "y"

    if is_ok:
        print("Great, thanks!")
    else:
        descriptions[all_games[index]["filename"]] = input("Please write an accurate description: ")

    add_to_metadata(filename, descriptions[filename])

    all_games[index]["reviewed"] = True
    

