import md5 from "https://cdn.skypack.dev/md5";

const challenges = [];
for await (const { name: path, isFile } of Deno.readDir("./")) {
  if (!isFile) continue;

  let [, index, name] = path.match(/([0-9]+)-(.+)\.json$/) ?? [];
  if (name === undefined) continue;
  index = +index;
  name = name.replace(/-/g, " ");
  const content = await Deno.readTextFile(path);

  const uniqueID = md5(content);
  const { exists, uploadURL, jsonFilename, id } = await fetch(
    `https://vt4x133ukg.execute-api.eu-west-1.amazonaws.com/default/getPresignedURL?id=${uniqueID}`
  ).then((r) => r.json());
  if (!exists) {
    await fetch(uploadURL, {
      mode: "cors",
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: content,
    });
  }

  challenges.push({ name, index, id });
}

challenges.sort((a, b) => a.index - b.index);

const out = `
/* GameLab's quest is a carefully curated sequence of challenges.
   THIS FILE WAS GENERATED BY gamelab/challenges/genQuest.js */
export default ${JSON.stringify(challenges, null, 2)};
`;
await Deno.writeTextFile("quest.js", out);
