import md5 from "https://cdn.skypack.dev/md5";

const currentChallenges = [
  `48044dbac8875315cdf85d8c1c5e03e2`,
  `7131c58b768762a68d05b1ce72373f71`,
  `c6faaa6fb82e1643d79231acfd547cf1`,
  `c3cee4344b09613cdff9ca992fa8b642`,
  `26312484f6b308582627698f2885cb64`,
  `7b8b193e409cdd5cc74135e9bff35e01`,
  `823d39de13ebd166511dd2b059382375`,
  `d9d39a4f69d3c6c07fe5978292dd2ef6`,
  `438e4864f1688bfd2784107a7db824de`,
  `b3f4c6862600550c2b9bef8613168498`,
  /* -- what did you just collide with!?! -- */
  `666aaba1d9cece4ea6343ce129d1c17b`,
  /* -- wrap game in func to restart on demand -- */
  /* -- multiple levels -- */
];

const challenges = [];
for await (const { name: path, isFile } of Deno.readDir("./")) {
  if (!isFile) continue;

  let [, index, name] = path.match(/([0-9]+)-(.+)\.json$/) ?? [];
  if (name === undefined) continue;
  index = +index;
  name = name.replace(/-/g, " ");
  const content = await Deno.readTextFile(path);

  const uniqueID = md5(content);
  const { exists, uploadURL, jsonFilename, id } = await fetch(
    `https://vt4x133ukg.execute-api.eu-west-1.amazonaws.com/default/getPresignedURL?id=${uniqueID}`
  ).then((r) => r.json());
  if (!exists) {
    await fetch(uploadURL, {
      mode: "cors",
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: content,
    });
  }

  challenges.push({ name, index, id });
}

challenges.sort((a, b) => a.index - b.index);

const out = `
/* GameLab's quest is a carefully curated sequence of challenges.
   THIS FILE WAS GENERATED BY gamelab/challenges/genQuest.js */
export default ${JSON.stringify(challenges, null, 2)};
`;
await Deno.writeTextFile("quest.js", out);
