
/* GameLab's quest is a carefully curated sequence of challenges.
   THIS FILE WAS GENERATED BY gamelab/challenges/genQuest.js */
export default [
  {
    "name": "jumpstart",
    "index": 0,
    "id": "b13ca2c2b9fe0580e1b1f71ecc1adaf2"
  },
  {
    "name": "crisis averted",
    "index": 1,
    "id": "48ff3b8fc0afbff9b917eb515282e9f2"
  },
  {
    "name": "left behind",
    "index": 2,
    "id": "710baa52aa1da8245feba8714a6b6c4e"
  },
  {
    "name": "whats the hold up",
    "index": 3,
    "id": "2227fd06204c96c0a0692fa7b8769ec8"
  },
  {
    "name": "all in order",
    "index": 4,
    "id": "6633a9d9f751e3cacd5799be883ba1ac"
  },
  {
    "name": "add bounce sound",
    "index": 5,
    "id": "6db84f68a296a536aa62a902d80fd6be"
  },
  {
    "name": "off the wall",
    "index": 6,
    "id": "d6c5d0ab4d7c8e450b69afce5d84be82"
  },
  {
    "name": "debarchery",
    "index": 7,
    "id": "82f418a0109533313c3344fb8007135f"
  },
  {
    "name": "hoppin rockets",
    "index": 8,
    "id": "06008275810963a143ead4a879b90bc9"
  },
  {
    "name": "animation_station",
    "index": 9,
    "id": "f060e1a85204e6a5c263b57a9590bc87"
  },
  {
    "name": "one jump",
    "index": 10,
    "id": "8ac4dd8e5791020bd11f673dd5c5727c"
  },
  {
    "name": "mile high club",
    "index": 11,
    "id": "6fd0b78fbe9b470c005690afee047a43"
  }
];
