name: Astro Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  astro-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
