name: Docker Build

on: # This workflow should run on...
  push: # a push...
    branches: # to one of these branches:
      - 'main'
  workflow_dispatch: # or when manually triggered
  pull_request:

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build Docker Image
        run: docker build -t sprig-ci .

