name: Unit Tests

on: # This workflow should run on...
  push: # a push...
    branches: # to one of these branches:
      - 'main'
  workflow_dispatch: # or when manually triggered
  pull_request:

permissions:
  contents: read

env:
  PUBLIC_MAX_LOOP_TIME_MS: 1500
  PUBLIC_MAX_ITERATIONS: 2000

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Execute Unit tests
        run: |
          yarn install --frozen-lockfile
          yarn run test:unit